- bin/centos71-devbuild.sh
- config/targets.yml
- kickstarts/base.ks.erb
- scripts/cli.rb
- scripts/kickstart_generator.rb
- scripts/vmbuild.rb
Summary of changes:
* Before, the build code worked with a single manageiq repository containing the build and system directories.
* Now, it works with 3 separate repositories (manageiq, manageiq-appliance (former system), and manageiq-appliance-build (former build)
* CLI now accepts 3 repos via -A(--appliance_url), -B(--build_url), and -M(--manageiq_url) or defaults to the ones in the manageiq organization.  The repo is not read from the targets.yml anymore.  The `--repo` option in the CLI was removed as it's now unclear with 3 repos.
* Note:  all 3 repos must have the `--reference` so you need to create branches and tags on each repo to do a build.
* Destination appliance will have manage-appliance checked out in /var/www/manageiq-appliance with a symlink from /var/www/miq/system -> …
> Test build/system directory to repo extraction

- kickstarts/base.ks.erb
We'll remove this symlink eventually, but this will get things working quicker.
> Add symlink to the old lib directory.

- kickstarts/base.ks.erb
* Clone manageiq.git into vmdb since the repo is the contents of vmdb.
This fixes the appliance build to work with the rerooted manageiq repo:
ManageIQ/manageiq#3363
* For some reason, DEBUG is set but empty in the kickstart ¯\_(ツ)_/¯. …
Unset it so ruby_parser doesn't print LOTS of output.
Fixes #5
> Fix appliance build after vmdb reroot

- docs/creating_build_vm.txt
Please review @abellotti @brandondunne 
It's the easiest thing I could find.  I don't think we care when at night it runs but it looks like it's defaulted to run every day around 3:05 AM.
I think that's ok and this makes the setup :cake: 
```
>  cat /etc/anacrontab
...
RANDOM_DELAY=45
START_HOURS_RANGE=3-22
#period in days   delay in minutes   job-identifier   command
1	5	cron.daily		nice run-parts /etc/cron.daily
7	25	cron.weekly		nice run-parts /etc/cron.weekly
@monthly 45	cron.monthly		nice run-parts /etc/cron.monthly
```
> Symlink the nightly build script to /etc/cron.daily.

- scripts/vmbuild.rb
- Merge John P's commit to add SHA256 checksums.
- Minor update:
* Only create the signatures if the needed GPG files exist on the build VM, not all build VMs will have those.
* Use manageiq_public.key for upstream builds.
> Add SHA256 checksums to VM based builds

- scripts/vmbuild.rb
Updated the vmbuild.rb script so that "latest" symlinks are created with relative path to the target directories.
This allows the latest links to be traversed from different VM build servers that cross mount the fileshare.
@jrafanie please review/merge.
@JPrause this will allow users to go to the kegerator subdirectory that they see off virtlab31 or aab-brewery7 and see and be able to click on the latest symlink.
> Use relative paths to the "latest" symlink.

- kickstarts/base.ks.erb
This is related to ManageIQ/manageiq-appliance#2 and ManageIQ/manageiq#792
No longer want to use the miqconsole instead of the getty.
Just use the default login.
Database first run no longer depends upon the no longer existant miqconsole service
/cc @abellotti @Fryguy
> dont autospawn appliance_console

- kickstarts/base.ks.erb
Adds cloud-init package and some configuration alterations to prevent the default config from preventing root ssh access and to log only to a file, rather than to the console.
> Add cloud init to appliance

- kickstarts/base.ks.erb
- Adding the openldap-clients package (ldapsearch, etc.), these tools are commonly
used when debugging manual configurations of OpenLDAP, certificates from directory
servers and such before diving into sssd.conf.
https://trello.com/c/SIOuHAMk/87-auth-3-support-ldap-authentication-via-sssd
> External Authentication - Adding support for LDAP

- kickstarts/base.ks.erb
I noticed some cleanup while testing pg94 in #19.
The only directories within COPY are now etc, var, and usr (we no longer have files we don't want to copy in opt) and we want to copy them all so let's blindly copy all files below COPY as that is most people would expect.
> Postgresql94 cleanup

- kickstarts/base.ks.erb
We used to run initdb and migrate the database as part of the kickstart
%post and had to configure normal shared memory but since we now setup
the database on first deployment boot, we shouldn't need this.
cc @carbonin @abellotti
> Remove extra shared memory needed for %post running PG setup.

- kickstarts/base.ks.erb
The wmic tool is needed to get running processes from windows machines.
This PR is also needed for https://github.com/ManageIQ/manageiq/pull/3540
https://bugzilla.redhat.com/show_bug.cgi?id=1233815
> Install wmi on appliance build.

- kickstarts/base.ks.erb
These commands don't belong in the kickstart.  Moved to cfme-setup.sh in https://github.com/ManageIQ/manageiq-appliance/pull/13
> Remove cloud-init config changes into cfme-setup.sh

- kickstarts/base.ks.erb
Depends on: https://github.com/ManageIQ/manageiq/pull/4082
@kbrock Please review, @Fryguy helped me on both 4082 and this one.
> v2_key no longer exists by default

- scripts/uploader.rb
- scripts/vmbuild.rb
It assumes we want to upload all of the appliances in a build directory.
We can clean this up further to incorporate the normal logger facility of the build script but this will allow us to upload when a nightly build completes.
We can also use the Build::Uploader class to upload release builds.
@Fryguy Please review
> Add fog based appliance build uploader which runs after each nightly.

- Rakefile
Note, it assumes you checkout manageiq as sister directories to manageiq-appliance-build.
> Fix precompile_assets post-reroot and productization move.

- kickstarts/base.ks.erb
manage-appliance repo shouldn't be in www root.
Related PRs:
* https://github.com/ManageIQ/manageiq-appliance-build/pull/33 [ clone repo in new location ] 
* https://github.com/ManageIQ/manageiq-appliance/pull/12  [set environment variable for new location]
* https://github.com/ManageIQ/manageiq/pull/4105 [use environment variable above]
> Appliance repo shouldn't be in www root.

- README.md
- bin/nightly-build.sh
- scripts/cli.rb
- scripts/vmbuild.rb
we don't want to upload nightlies as release builds from all VM build machines,  only from the
real build machine, i.e. if run from the cron via bin/nightly-build.sh.  Also updated README.md for the
required fog gem.
> Add new --upload option

- Rakefile
This allows us to remove some of the downstream specifics from the Rakefile in a follow up PR.
> Add support for lib/tasks

- scripts/vmbuild.rb
@jrafanie 
Fix for:
/build/scripts/vmbuild.rb:92:in `block in <main>`: uninitialized constant Target (NameError)
from /build/scripts/vmbuild.rb:92:in `collect`
from /build/scripts/vmbuild.rb:92:in `<main>`
> Fix uninitialized constant error for Target class

- Rakefile
version number given can be "5.5.0.1-alpha1".  For tar file, only take the numbers up to '-'.
> Take version number up to '-' for tar file

- bin/nightly-build.sh
- bin/release-build.sh
- bin/shared_functions.sh
From a build vm, you can now build any tag or branch (release) found on each of
the repositories, manageiq, manageiq-appliance, and
manageiq-appliance-build by running:
`./release-build.sh capablanca-1-alpha1`
cc @abellotti @carbonin @simaishi @Fryguy 
Note, this assumes you want to upload the release to the website also.
> Add release build script

- kickstarts/partials/post/systemd.ks.erb
Added the line in the kickstart post section to enable the service that runs the script to determine which cloud-init datasources to use on boot.
For https://github.com/ManageIQ/manageiq-appliance/pull/20
> Added enable for cloud-init datasource check

- Rakefile
Updated downstream build wiki to include instruction on how to install node, gulp and bower on build machine.
@Fryguy
> Add self service UI build

- kickstarts/partials/post/systemd.ks.erb
We don't need it and it makes configuring static IPs by editing files by hand less reliable.
> Stopped and disabled NetworkManager

- kickstarts/partials/post/systemd.ks.erb
The service will be enabled and started after the database is configured
by the changes in https://github.com/ManageIQ/manageiq/pull/4989
https://bugzilla.redhat.com/show_bug.cgi?id=1272604
> Remove the line that enables evmserverd

- Rakefile
- config/tarball/exclude
Not sure if there is a better/cleaner way to handle exclusion from exclusion for tar creation (exclude everything in tmp except for sti_loader.yml)..
@jrafanie @Fryguy
> Compile sti loader and keep yml in tar

- kickstarts/base.ks.erb
Ensures that we will have valid interface configuration at first boot.
@simaishi @bdunne @abellotti @gtanzillo
> Put the DEVICE line in ifcfg files if missing

- kickstarts/base.ks.erb
- scripts/cli.rb
- scripts/spec/cli_spec.rb
- scripts/spec/target_spec.rb
- scripts/target.rb
- scripts/vmbuild.rb
Tested by building/deploying hyperv and vsphere images with this change.
Note: Depending on the version of qemu-img on the machine, the final image could be the same size as the disk size.  CentOS 7.1 produced 40GB image, Fedora22 produced 3.8GB image.  Use -o to limit type of images to build as needed.
> Add vhd support for Hyper-V/SVCMM

- kickstarts/base.ks.erb
The original PR used `&&` in place of `||`
https://bugzilla.redhat.com/show_bug.cgi?id=1276706
> Fix the line that conditionally prints DEVICE=

- kickstarts/base.ks.erb
The current scap-security-guide remediations for the sshd_config
file don't check if there is a new line and append fixes anyway.
This will cause the first fix to share a line with whatever is
at the end of the file.
https://bugzilla.redhat.com/show_bug.cgi?id=1219230
https://bugzilla.redhat.com/show_bug.cgi?id=1219227
https://bugzilla.redhat.com/show_bug.cgi?id=1219231
https://bugzilla.redhat.com/show_bug.cgi?id=1219229
https://bugzilla.redhat.com/show_bug.cgi?id=1219228
> Add a new line to /etc/ssh/sshd_config

- kickstarts/partials/packages/includes.ks.erb
We need this because we fail to start the app without syncing the time settings.
> Add chrony package to include list

- bin/release-build.sh
- scripts/cli.rb
- scripts/spec/cli_spec.rb
- scripts/vmbuild.rb
'release' builds will put the images to 'upstream_stable' directory. 'nightly' will continue to put the images to 'upstream' directory.
@Fryguy @jrafanie please review.
> Added 'release' type for build options

- kickstarts/partials/post/systemd.ks.erb
These commands don't do anything as the post is executed
in a chroot environment.
This prevents errors in anaconda-post.log of the form:
```
+ systemctl restart systemd-journald
Running in chroot, ignoring request.
```
> Remove service start and stop from post section

- kickstarts/base.ks.erb
We don't need a session store in anaconda so force Rails to use memory store
since rails 5 mem_cache_store tries and fails to connect to a not running
memcached.
Depends on: https://github.com/ManageIQ/manageiq/pull/6751
> Use memory store since loading rails 5 fails to connect to memcached.

- kickstarts/partials/post/db_init.ks.erb
This is needed because the environment rake task will fail if the memcache server is not running.
Motivated by the same issue as https://github.com/ManageIQ/manageiq-appliance-build/pull/92
> Add memcached to Requires= and After= in appliance-initialize

- scripts/cli.rb
- scripts/spec/cli_spec.rb
- scripts/vmbuild.rb
https://github.com/ManageIQ/manageiq-appliance-build/issues/95
This PR will make building development image to test proposed changes simpler.
This will be done by adding optional command line arguments where specific branch names
can be specified for each of the repos.
No default behavior is changing.
> Optionally allow a different branch for each repo

- kickstarts/partials/post/systemd.ks.erb
Some rake tasks require the session store to be active even before the application starts.
@jrafanie @simaishi
> Enable memcached in kickstart post

- README.md
- Build machines based on CentOS 7.2
- Additional steps needed for building Hyper-V images
> Updated instructions for build machines to be CentOS 7.2 based

- scripts/spec/cli_spec.rb
- scripts/spec/target_spec.rb
- scripts/target.rb
The instruction has been updated to put newer version of qemu-img to get reasonable size .vhd image (thanks @abellotti )
> Build hyperv by default

- kickstarts/partials/packages/includes.ks.erb
This will allow us to mount Samba shares for database backups
http://talk.manageiq.org/t/schedule-db-backup-samba-issue/1209
https://bugzilla.redhat.com/show_bug.cgi?id=1313958
@gtanzillo @jvlcek
> Install cifs-utils package

- kickstarts/partials/main/disk_layout.ks.erb
I think 4680 was a typo of 4608 (4.5 GiB)
@jrafanie Because it was bothering me and @simaishi
> Make the root filesystem a size that makes sense

- kickstarts/partials/post/repos.ks.erb
Previously we were getting redirected for the abellott repo and getting a certificate error on the scl copr repo.
This meant that we would not have the copr postgres repo enabled on the appliance.
We were getting the following output in `anaconda-post.log`:
For the manageiq-scl (abellott) repo:
```plain
+ wget https://copr.fedoraproject.org/coprs/abellott/manageiq-scl/repo/epel-7/abellott-manageiq-scl-epel-7.repo
--2016-03-08 20:29:27--  https://copr.fedoraproject.org/coprs/abellott/manageiq-scl/repo/epel-7/abellott-manageiq-scl-epel-7.repo
Resolving copr.fedoraproject.org (copr.fedoraproject.org)... 140.211.169.196, 66.35.62.162, 209.132.181.16, ...
Connecting to copr.fedoraproject.org (copr.fedoraproject.org)|140.211.169.196|:443... connected.
HTTP request sent, awaiting response... 302 …
```
> Use the fedorainfracloud URLs to download the .repo files

- kickstarts/partials/packages/includes.ks.erb
- Apache module needed for SAML external authentication - mod_auth_mellon
Trello: https://trello.com/c/YIUK4qLT
> [auth] Adding support for SAML

- kickstarts/base.ks.erb
- kickstarts/partials/main/bootloader.ks.erb
- kickstarts/partials/packages/includes.ks.erb
- kickstarts/partials/post/azure.ks.erb
- kickstarts/partials/post/systemd.ks.erb
This PR contains kickstart related changes for Azure appliance (disk layout will be revisited/modified later).
- No ipv6
- Modify boot loader options (output to serial port, rootdelay)
- Add hyperv drivers
- No cloud-init
- Install/configure WALinuxAgent (Swap space, deprovision, SSH ClientAliveInterval)
The other changes needed for scripts are not yet completed. Putting this PR now, so downstream build can take advantage of this change, as per discussion with @Fryguy
> Kickstart file related changes needed to create an appliance for Azure

- kickstarts/base.ks.erb
This will allow us to see the output from commands run in the `%post` section in `anaconda-post.log`.
Previously they were being sent to `/dev/tty3` and not stdout so they would not be seen by the `--log` directive.
@abellotti This is the only thing I could get to work outside of removing the `/dev/tty3` stuff entirely.
It's not pretty, but it will be much easier to diagnose build failures this way.
@JPrause FYI
> Direct output from post to both stdout and tty3

- kickstarts/partials/packages/includes.ks.erb
npm is no longer needed solely for self service, bower also depends on it
Closes #117
> Expand misleading comment on npm package include

- kickstarts/base.ks.erb
- kickstarts/partials/main/bootloader.ks.erb
- kickstarts/partials/main/network.ks.erb
- kickstarts/partials/post/gce.ks.erb
Log kernel and syslog messages to /dev/ttyS0, so you can debug with gcloud compute instances get-serial-port-output.
> Adding support for building gce appliance

- kickstarts/partials/post/ui_compile.ks.erb
Because the version of npm available via RPM is only 1.3.6,
and some of the self-service dependencies need npm 3.*,
we'll use the RPM-installed npm to install a current npm version.
Should address https://github.com/ManageIQ/manageiq/issues/8023 and https://github.com/ManageIQ/manageiq/issues/7801
> ui_compile - install (newer) npm via npm

- kickstarts/partials/packages/includes.ks.erb
Add the glusterfs-fuse package in order to support SSA for Gluster
based VMs on RHEV.
> Add glusterfs-fuse package.

- kickstarts/base.ks.erb
- kickstarts/partials/post/bundler.ks.erb
- kickstarts/partials/post/ui_compile.ks.erb
To prevent `Could not find sass-3.4.21 in any of the sources (Bundler::GemNotFound)` when running `gulp build`.
We do technically run `bundle install` from within `npm install`, but it seems it's run in a clean environment and doesn't work reliably, this should.
https://bugzilla.redhat.com/show_bug.cgi?id=1329761
@simaishi could you verify that this fixes the problem please? There should be no more GemNotFound in the log, *and* `/var/www/miq/vmdb/public/self_service/styles/app-*.css` should be about 12 kB (instead of almost empty).
> Run `bundle install` under self_service too

- bin/nightly-build.sh
- bin/release-build.sh
- scripts/cli.rb
- scripts/vmbuild.rb
Added an option to specify the image upload directory, to allow nightly/release builds from different branches.
This PR will change where the images will be uploaded to and how symlinks are created.  This is aligned with the internal file share structure change @bdunne is working on.
Currently:
- **upstream** dir for any **nightly** build, **latest** symlink for the latest nightly build
- **upstream_stable** dir for any **release** build, **latest** symlink for the latest release build
With this change:
- **master** dir for **nightly** build for **master** branch, **latest** symlink for the latest nightly build
- **\<branch>** dir for **nightly** and **release** builds for **\<branch>**, **latest** symlink for the latest nightly build and **stable** symlink for the latest **release** …
> Change upload directory to allow nightly from different branches

- kickstarts/partials/post/ruby_install.ks.erb
cc @bdunne @Fryguy
I'm thinking darga should go out with the latest 2.2.x ruby.
> Use ruby 2.2.5 for appliance builds.

- config/base_azure.tdl
- kickstarts/partials/main/disk_layout.ks.erb
- scripts/spec/cli_spec.rb
- scripts/spec/target_spec.rb
- scripts/target.rb
- scripts/vmbuild.rb
The remaining item is to change disk_layout.
Currently, applinaces have ~6GB swap space on the 40GB disk (--size=4096 --grow).  When a VM is created in Azure, Azure gives an additional disk that can be used to store temporary data at no extra cost (the primary use of this disk is cache/swap). So for Azure, that's where swap will be created:
https://github.com/ManageIQ/manageiq-appliance-build/blob/master/kickstarts/partials/post/azure.ks.erb#L3
(set swap to be 10GB for now)
We have a few options for that ~6GB not needed for Azure:
1. Reduce the overall disk size by ~6GB
1. Keep the disk size as is, and increase size on different volume(s) (which one?)
1. Leave everything as is, which makes the swap to be 16GB
1. Don't create swap on temporary storage and make it consistent with other …
> Add azure image build

- bin/nightly-build.sh
- scripts/docbuild.rb
This builds the docs on a nightly basis with some current restrictions...
- Only master branch
- Only the lastest (i.e. not docs per timestamp)
- Doesn't upload to the website yet, only to the fileshare
> Add doc builds to nightly build

- scripts/uploader.rb
- scripts/vmbuild.rb
Now we have 'darga' nightly, we can't rely on the word 'master' being in the file name to determine if it's a nightly build or not.
@abellotti @Fryguy please review
> Use build type to determine nightly or release

- kickstarts/partials/post/azure.ks.erb
With this change, the only way allowed to login to appliance will be using ssh key.
https://bugzilla.redhat.com/show_bug.cgi?id=1339677
> Disable password authentication for Azure

- kickstarts/partials/main/repos.ks.erb
- kickstarts/partials/packages/includes.ks.erb
- kickstarts/partials/post/repos.ks.erb
This repo seems to be updated more frequently than the copr repo and contains more recent packages.
This will also allow us to pull PostgreSQL 9.5, which the other repo did not have.
> Use the centos.org repo for scl packages

- kickstarts/base.ks.erb
Some things that are done during the build process have the potential to print to the logs.
None of this should be present when the machine is deployed for the first time.
https://bugzilla.redhat.com/show_bug.cgi?id=1286793
> Clean the rails log directory in the kickstart post

- kickstarts/partials/packages/includes.ks.erb
We require lvm2 to be installed when initializing the database so it should be explicitly included in the kickstart.
https://bugzilla.redhat.com/show_bug.cgi?id=1343007
> Explicitly include lvm2 package

- kickstarts/partials/packages/includes.ks.erb
`libcurl-devel` is needed by `curb` gem which is a dependency of `ovirt-engine-sdk` added in https://github.com/ManageIQ/manageiq/pull/9521
Fixes https://github.com/ManageIQ/manageiq/issues/10234
> Add libcurl-devel, needed by curb

- kickstarts/partials/post/ruby_install.ks.erb
Purpose or Intent
-----------------
Update appliances to 2.3.1.
Ruby 2.3.1 is the latest stable release of ruby and is mostly compatible with 2.2.5 but offers some new features such:
* frozen string literals
* lonely `&.` operator (safe navigation operator, similar to Hash#fetch_path)
* did_you_mean gem for useful errors
* indented heredoc
* Clearer ArgumentError message:
```
2.2.5: wrong number of arguments (0 for 1..3)
2.3.1: wrong number of arguments (given 0, expected 1..3)
```
* more, see below
Links
-----
* [summary of ruby 2.3.1 changes](https://github.com/ruby/spec/issues/175)
We can start using ruby 2.3.1 before or after https://github.com/ManageIQ/manageiq/pull/8488 is merged.
Related:
https://github.com/ManageIQ/manageiq/issues/9829
> Upgrade ruby 2.2.5 to 2.3.1

- .gitignore
- README.md
- config/base.json
- config/imagefactory.conf
- config/ova.json
- config/target.json
- kickstarts/base.ks.erb
- kickstarts/partials/post/vagrant.ks.erb
- scripts/kickstart_generator.rb
- scripts/spec/cli_spec.rb
- scripts/spec/kickstart_generator_spec.rb
- scripts/spec/target_spec.rb
- scripts/target.rb
- scripts/vmbuild.rb
This patch series adds support for building Vagrant "boxes". There's two patches in the series, one prepares support for multiple OVA formats, and the second patch uses that to add in Vagrant support.
Vagrant boxes are (Vagrant) provider specific. This builds a box for the VirtualBox provider, which is the most common one. Other formats can be added later. Also no upload to Atlas is implemented yet.
> Add support for building Vagrant appliances.

- README.md
- kickstarts/partials/packages/includes.ks.erb
- scripts/spec/cli_spec.rb
- scripts/spec/target_spec.rb
- scripts/target.rb
Add support for building libvirt and GCE appliance.
These are two separate commits but in one PR. The commits step on each other so it's easier to have it in one PR.
> Add support for libvirt and GCE

- kickstarts/base.ks.erb
- kickstarts/partials/main/bootloader.ks.erb
- kickstarts/partials/main/network.ks.erb
- kickstarts/partials/post/aws-ec2.ks.erb
Undo cloud-init cfg settings that come from manageiq-appliance repo.
For AWS EC2, need to disable root/password login, and only allow ssh key access.
The default user cloud-init creates on CentOS is "centos".
Requires https://github.com/ManageIQ/manageiq-appliance/pull/87
@Fryguy @carbonin please review
> Add kickstart file changes for AWS EC2

- scripts/vmbuild.rb
Old code (all run as subshells):
git reset --hard
git clean -dxf
git checkout <ref>
git fetch origin
git reset --hard origin/<ref>
The last line only works when the --reference <ref> parameter is a
branch. The build does not fail though, because a subshell failing
doesn't exit the Ruby interpreter. So the code was in essence a NOP in
case of a branch.
However, if I understand the old code correctly, there is another issue.
If you build from a new tag for the first time, the code would actually
not build that tag but whatever was there before. This is because the
"git fetch" is done after the "git checkout <ref>". This could actually
have lead to releases that don't correspond to their tag :-D
The new code looks like this:
rm -rf /build/references/<ref>
chdir /build/references/<ref>
git …
> Fix when building from tag

- kickstarts/partials/main/db_fs.ks.erb
This will allow us to upgrade postgresql versions more easily by creating the new data directory next to the old one on the same volume.
This will allow us to mount the volume at the new path (e.g. `/var/opt/rh/rh-postgresql95/lib/pgsql`) while also having separate data directories for the upgrade and allowing us to use hardlinks to perform the upgrade to save space on the disk.
@jrafanie please review
/cc @gtanzillo @Fryguy
> Change postgres disk mountpoint

- kickstarts/partials/post/ui_compile.ks.erb
EPEL now has npm v3.10.3 and there is no need to update npm now.
Having this line causes build failure.
> Remove npm updating itself

- kickstarts/partials/packages/includes.ks.erb
This is needed for the 2nd lever proxying of VNC/SPICE consoles.
needed by https://github.com/ManageIQ/manageiq/pull/11273
ping @simaishi: need this for Euwe :-(
> Add socat RPM to installed packages.

- kickstarts/partials/main/repos.ks.erb
- kickstarts/partials/post/repos.ks.erb
'wmi' package was forked from 'abellott' account into 'manageiq' account
@bdunne The new repo also contains freeipmi 1.5.1-2 for:
https://bugzilla.redhat.com/show_bug.cgi?id=1381655
https://github.com/ManageIQ/manageiq/issues/6052
> Use 'manageiq' copr account to host RPM

- kickstarts/partials/packages/includes.ks.erb
This is the proper name for a package built for SCL
Fixes #145
Requires #174 
https://bugzilla.redhat.com/show_bug.cgi?id=1383795
> Change the name of the repmgr package

- kickstarts/partials/packages/includes.ks.erb
These fonts are then used by prince to create PDF reports
in Chinese and Japanese locales.
https://bugzilla.redhat.com/show_bug.cgi?id=1386217
> Add Chinese and Japanese fonts for PDF reports

- kickstarts/partials/main/repos.ks.erb
- kickstarts/partials/post/repos.ks.erb
master PR: https://github.com/ManageIQ/manageiq-appliance-build/pull/174
'wmi' package was forked from 'abellott' account into 'manageiq' account
The new repo also contains freeipmi 1.5.1-2 for:
https://bugzilla.redhat.com/show_bug.cgi?id=1381655 (master)
https://bugzilla.redhat.com/show_bug.cgi?id=1383368 (darga)
(cherry picked from commit c98e44be9447f2885e916073e1f3cb163b42f02e)
> [DARGA] Use 'manageiq' copr account to host RPM

- bin/kickstart_build.rb
- kickstarts/partials/packages/includes.ks.erb
- kickstarts/partials/post/bundler.ks.erb
- kickstarts/partials/post/source_setup.ks.erb
- kickstarts/partials/post/ui_compile.ks.erb
- scripts/cli.rb
- scripts/kickstart_generator.rb
- scripts/spec/cli_spec.rb
- scripts/spec/kickstart_generator_spec.rb
- scripts/vmbuild.rb
Split to 2 commits:
eebebde - to rename the actual directory/repo used
964c58b - everywhere else used internally in variables, etc. to make it consistent (doesn't affect the resulting appliance)
There will be another PR that will follow this, to update the SUI build steps needed on 'master' (unrelated to the rename).
> Rename ssui repo

- README.md
- kickstarts/partials/main/bootloader.ks.erb
- kickstarts/partials/main/network.ks.erb
When target name was changed from 'aws-ec2' to 'ec2' in https://github.com/ManageIQ/manageiq-appliance-build/pull/161, 2 files got missed.
Also fixed README.
> Change target from 'aws-ec2' to 'ec2' in partials

- kickstarts/partials/main/repos.ks.erb
- kickstarts/partials/packages/includes.ks.erb
- kickstarts/partials/post/repos.ks.erb
This will allow us to provide different packages for different versions of ManageIQ
Also, there is a new version (1.2.1) of the pglogical package provided in this repo.
https://www.pivotaltracker.com/story/show/125274621
@simaishi @gtanzillo please review
> Use a single versioned repo to pull rpms built by us

- kickstarts/partials/packages/includes.ks.erb
It is required for the build and was not previously required explicitly.
It must have been being included as a dependency at some point, but is longer present on appliances which is preventing us from downloading the copr repo files we need.
The `manageiq-ManageIQ-Fine-epel-7.repo` file is missing and I am seeing the following in `anaconda-post.log`
```
'/var/www/miq/lib' -> '/var/www/miq/vmdb/gems/pending'
+ [16:44:15] pushd /etc/yum.repos.d/
/etc/yum.repos.d /
+ [16:44:15] wget https://copr.fedorainfracloud.org/coprs/manageiq/ManageIQ-Fine/repo/epel-7/manageiq-ManageIQ-Fine-epel-7.repo
/tmp/ks-script-NH0n_X: line 104: wget: command not found
+ [16:44:15] popd
```
This also seems to affect euwe.
> Add the wget package

- kickstarts/partials/post/ui_compile.ks.erb
Remove explicit gulp install and replace `gulp build` with new webpack
version of build process. `yarn run build` will kick off the `build`
task designated in `package.json` which will compile the build using the
configuration from `config/webpack.prod.js` in the manageiq-ui-service
directory.
@miq-bot add_label euwe/no
Dependent on ManageIQ/manageiq-ui-service#420
> Update Service UI build command

- kickstarts/partials/post/source_setup.ks.erb
Vagrant for Darga is built using vmbuild.rb from 'master' branch.
Use sui_checkout instead of ssui_checkout.
> [DARGA] SSUI -> SUI change for vagrant

- kickstarts/partials/main/repos.ks.erb
- kickstarts/partials/packages/includes.ks.erb
- kickstarts/partials/post/ruby_install.ks.erb
Use the ruby-install rpm here https://copr-be.cloud.fedoraproject.org/results/postmodern/ruby-install/fedora-25-x86_64/00492646-ruby-install/
This way we don't have to build ruby-install from source every time we build an appliance.
> Install ruby-install from rpm rather than from source

- kickstarts/partials/post/ec2.ks.erb
When .vhd file is imported to EC2 and AMI is created (using `aws ec2 import-image`), a part of the process boots the image which runs cloud-init.  cloud-init finds an ephemeral disk (which I think the AMI creation process adds - there is no log for the import and I can't tell exactly what happens) and add a line to /etc/fstab:
`/dev/xvdb	/mnt	auto	defaults,nofail,comment=cloudconfig	0	2`
This is due to default cloud-init behavior of mounting an ephemeral disk as /mnt.  The import process finishes, the ephemeral disk is disconnected and now AMI is created with just 1 disk.
Then, a user creates an instance from this AMI with an (non ephemeral) external disk.  Since fstab already contains the line for mounting /dev/xvdb as /mnt, it tries to mount the external disk as /mnt, which will break …
> Disable mounting ephemeral disk in cloud-init for EC2

- kickstarts/partials/post/source_setup.ks.erb
The directory rooted at $app_root/vmdb/gems/pending has been moved
into a separate gem and is no longer present at that path.
We will not be updating the link location every time the gem
changes versions or we track a new git sha so I'm removing this.
> Remove the symlink that used to point to gems/pending

- scripts/uploader.rb
The uploader script was uploading the 'release' images with `.gz` extension for GCE images, rather than `.tar.gz` which is required by GCE.
`name[-1]` is `<sha>.<ext>` (e.g. `e286988bff.tar.gz`, `e286988bff.ova`)
> Fix gce image upload which has .tar.gz as extension

- kickstarts/base.ks.erb
Previously the quotes were preventing this from working properly.
We should only quote the variable.
> Correct line to remove logs from the appliance

- kickstarts/partials/packages/includes.ks.erb
They're required for logrotate feature to work, and adding explicitly makes it easier to see what packages are required when working on non-VM appliance (https://github.com/ManageIQ/manageiq-pods/pull/109)
> Explicitly add cronie and logrotate packages

- kickstarts/partials/packages/includes.ks.erb
- kickstarts/partials/post/gce.ks.erb
Google compute engine packages have changed and that's causing SSH login not to work any more.  
There are 2 issues:
1. One of the packages, `google-compute-engine-init`, enables/starts services using systemctl in RPM post script.  However the rpm doesn't require `systemd` and `google-compute-engine-init` gets installed before `systemd`, causing %post to fail. Because of this, the service that creates a user account to allow SSH access doesn't get enabled/started.
1. After installing the RPMs, initial setup runs.  Some of the steps try to retrieve metadata info or configure network, which doesn't work in ImageFactory/oz environment. Need to disable those steps.
The changes made are:
- moved package installation to kickstart %post section
- created `instance_configs.cfg.template` to …
> Update google compute engine package installation to allow SSH login

- kickstarts/partials/post/db_init.ks.erb
This is more similar to what the container build does and allows us to remove the v2_key generation from initialize_appliance.sh
> Generate the v2_key when we create the database

- kickstarts/partials/packages/includes.ks.erb
Newer version of nodejs (v6.10.3) has added dependency for `libhttp_parser` library.  Without explicitly adding http-parser, the build picks up outdated `nodejs010-http-parser` package which causes issue.
cc @chriskacerguis
> Install http-parser package

- kickstarts/partials/post/bundler.ks.erb
This will add the appliance gems like appliance_console into the same bundle used by the application
Requires https://github.com/ManageIQ/manageiq-appliance/pull/125
/cc @chessbyte @bdunne
> Link the appliance gem dependencies into bundler.d before bundle install

- kickstarts/partials/post/vagrant.ks.erb
Fixes an issue raised in [ManageIQ Talk](http://talk.manageiq.org/t/ruby-missing-in-vagrant-miq/2516).
While looking at it, noticed `ap` has similar problem, so fixed that as well.
> Use root login shell to run appliance_console in vagrant

- kickstarts/partials/post/firewalld.ks.erb
Before this change appliances would not correctly receive IPv6 addresses via DHCP.
https://bugzilla.redhat.com/show_bug.cgi?id=1473366
/cc @simaishi
> Allow the DHCPv6 client through the appliance firewall

- scripts/vmbuild.rb
Each nightly/release build uses about 180GB in STORAGE_DIR.  Multiple files are created during a build for each target, but only the final image is what we'd need to keep.
We clean up STORAGE_DIR daily using [clean_imagefactory_storage.sh](https://github.com/ManageIQ/manageiq-appliance-build/blob/master/bin/clean_imagefactory_storage.sh) so they're deleted anyway the next day. This change will clean up those files after each build rather than waiting for a day.
I know storage isn't that expensive now... but I have personally never used any of those temporary files within 24 hours after the build, and I didn't see a need to keep them around for a day.
> Delete temporary files created during build

- kickstarts/partials/post/ui_compile.ks.erb
Mirrors the change in https://github.com/ManageIQ/manageiq/pull/15578
> Use update:ui task, instead of update:bower

- scripts/fix_azure_disk.rb
Azure now requires .vhd image to be in fixed format and aligned to nearest 1MB (See "General Linux Installation Notes" in https://docs.microsoft.com/en-us/azure/virtual-machines/linux/create-upload-generic).  This script does the resize/conversion.
Additional change will be required for upstream and downstream separately to actually call this script, along with other needed changes. raw image will be passed for upstream and vpc image will be passed for downstream.
For upstream, I'm having a problem finding`qemu-img` that works end-to-end.
- `>= 2.6.0` is needed for vpc conversion to work properly
- `= 2.6.0` gives an issue with imagefacory in our nested build environment (https://bugzilla.redhat.com/show_bug.cgi?id=1456407)
and 2.6.0 is the latest I can find for CentOS... …
> Add a script to resize/convert Azure image

- kickstarts/partials/packages/includes.ks.erb
- kickstarts/partials/post/systemd.ks.erb
We're not in a situation where we can support either a clustered
redis instance or a single instance which all of our appliances
would point at. These cases would require more management and
configuration than we are prepared to tackle.
The distributed case also will not work because the websocket push
notification would be inserted on the redis instance local to the
server which generated it. This would not necessarily be the same
redis instance which the websocket worker would be watching.
cc @bdunne @skateman
> Remove the redis package

- kickstarts/partials/post/ruby_install.ks.erb
This also adds the `gem env gemdir` bin path to the $PATH using /etc/default/evm
This allows us to find bin files provided by git-based gems
This will allow the appliance console to work after the gem split.
> Install ruby with --system so that bin files are easier to find

- kickstarts/partials/post/ruby_install.ks.erb
Without this we're getting the following when trying to run gem during the kickstart process:
++ [18:11:21] gem env gemdir
/tmp/ks-script-Kv98jD: line 125: gem: command not found
> Add /usr/local/bin to the PATH after installing ruby

- kickstarts/partials/post/source_setup.ks.erb
this helps QE and developers to identify the correct build date of upstream appliances
related PR https://github.com/ManageIQ/manageiq/pull/16196
> add BUILD file to miq checkout

- config/base.tdl
- config/base_azure.tdl
- kickstarts/partials/main/disk_layout.ks.erb
This PR increases the `/` filesystem from 4.5GiB to 10GiB and the `/var` filesystem from 2GiB to 12GiB
The root filesystem change is needed so that upgrades can be performed by using `bin/update` as described in #219. In this case the new gems being installed in `/opt/rubies/ruby-2.3.1/lib/ruby/gems` were filling up the space on the root filesystem.  It should be noted that after upgrading the appliance, we can run `bundle clean --force` to remove old versions of updated gems and reclaim some space.
The `/var` filesystem change is needed so that we can use embedded ansible. Both the rpm and docker versions require more space. The rpm version has an explicit check which requires at least 10GiB of free space on the `/var` partition. We currently ignore that check …
> Increase filesystem sizes

- config/base.tdl
- config/base_azure.tdl
Closes https://github.com/ManageIQ/manageiq-appliance/issues/137
I will put a follow up PR to use just 1 tdl file for all images. It's probably not worth keeping 2 files, just to save 5GB disk size. (As you can see in the diff, I forgot to update azure one when we went from 7.2 to 7.3!)
The new ISO is already on the build machine.
> Update to CentOS 7.4

- kickstarts/partials/post/bundler.ks.erb
Due to issues we're running into with bundler 1.16, locking to 1.15.4 for now.
> [GAPRINDASHVILI] Lock bundler to 1.15.4

- kickstarts/partials/post/systemd.ks.erb
This is only needed when we are running the embedded ansible
role so we can do it from the worker
> Remove enable for docker service

- README.md
- scripts/vmbuild.rb
Changing path to config files to be relative to the vmbuild.rb script, rather than hard-coded `/build/config` as `config` dir contains files committed to git, which could be different for different branches
> Change config path to be relative to script

- kickstarts/partials/post/bundler.ks.erb
This will remove any duplicate gems that we have that were installed
with the system ruby (for example, minitest).
This was causing the following warning when starting the appliance_console
```plain
WARN: Unresolved specs during Gem::Specification.reset:
minitest (~> 5.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
```
/cc @JPrause
> Run `bundle clean --force` after we `bundle install`

- kickstarts/partials/post/bundler.ks.erb
It's needed to load `rest-client` in irb/automate.  For bundle, we override with local path 'mime-types-redirector'
https://bugzilla.redhat.com/show_bug.cgi?id=1518865
> Install 'mime-types' outside of bundle

- kickstarts/partials/post/bundler.ks.erb
EPEL currently has qpid-proton-c 0.17.0. With this version of RPM, it fails to compile qpid_proton gem (v0.18.1). Marking as WIP until 0.18.x becomes available in EPEL.  0.18.1 is currently in epel-testing and gem install works with that version.
cc @gberginc @Fryguy @chargio
> Add qpid_proton to bundle install

- kickstarts/partials/post/ui_compile.ks.erb
Clearing yarn cache reduces the uncompressed image size by ~800MB
Uncompressed 'master' images (hyperv, azure, etc.) are now so big that it exceeds rackspace size limit and not being uploaded there since February... We should/can probably clean up more, but starting with this easy one.
> Clear yarn cache

- scripts/vmbuild.rb
Create a release ref symlink (e.g. gaprindashvili-1) on fileshare, so we can easily find released builds later...
> Create ref symlink for release build

- kickstarts/base.ks.erb
"server-policy" yum group doesn't exist on CentOS 7.
Up until now, having that entry in kickstart didn't cause any issue. It logged:
`13:01:02,893 CRIT yum.YumBase: Warning: Group server-policy does not have any packages to install.`
and build continued. But now, the build prompts for yes/no and times out waiting for an answer.
> Remove non-existing "server-policy" yum group

- kickstarts/partials/main/repos.ks.erb
- kickstarts/partials/packages/includes.ks.erb
This PR adds a repo(`https://rpm.nodesource.com/pub_8.x/el/7/x86_64/`) during build from which we can install an rpm (`nodesource-release`) which brings a repo file which allows us to install nodejs version 8.
This also removes npm because the new node package also provides `/usr/bin/npm`
```
[root@localhost vmdb]# rpm -qa | grep node
nodesource-release-el7-1.noarch
nodejs-8.11.3-1nodesource.x86_64
[root@localhost vmdb]# rpm -qa | grep npm
[root@localhost vmdb]# which npm
/usr/bin/npm
[root@localhost vmdb]# yum provides /usr/bin/npm
2:nodejs-8.11.3-1nodesource.x86_64 : JavaScript runtime
Repo        : nodesource
Matched from:
Filename    : /usr/bin/npm
1:npm-3.10.10-1.6.14.3.1.el7.x86_64 : Node.js Package Manager
Repo        : epel
Matched from:
Filename    : /usr/bin/npm
```
cc @himdel
> Update to node 8

- config/ova.json
- kickstarts/base.ks.erb
A few changes for vSphere appliance image.
For https://bugzilla.redhat.com/show_bug.cgi?id=1429653:
- Changed hardware version to vmx-10 (was: vmx-7/vmx-8)
- Changed network to VmxNet3 (was: E1000)
- Added paravirtual drivers
I didn't make the default driver to be paravirtual in OVA (default: LSI Logic) as that will make the image not to work on Fusion 10. Since the drivers are now included in the image, anyone wanting to use paravirtual can just change the setting once imported to vSphere.
For https://bugzilla.redhat.com/show_bug.cgi?id=1614006:
- Set OS type to `centos64Guest` (requires imagefactory [c78579f](https://github.com/redhat-imaging/imagefactory/commit/c78579ff3e7e3ed5fa79fab912968381d486f608) or later). OS will show as `CentOS 4/5/6/7 (64-bit)` in vSphere and `CentOS 64-bit` …
> Update vSphere ova

- kickstarts/partials/post/ruby_install.ks.erb
@simaishi I just noticed this is still 2.3.1... figured we wanted 2.4.4 on master/hammer, right?  Are there other places that need to be bumped to match what's available downstream?
> Update appliances to ruby 2.4.4

- README.md
- scripts/spec/target_spec.rb
- scripts/target.rb
- scripts/vmbuild.rb
We now need to compress some of the images as the image size is growing... This PR is adding an optional post-build compression support, taken from Geert's https://github.com/ManageIQ/manageiq-appliance-build/pull/167 with a few changes:
- Don't use hard links when compressing/moving image files as source and destination could be on different devices
- Delete original file after compression for gzip
- Don't pass file_name for scp target as file_name will be different for compressed images
> Add post compression support

- scripts/target.rb
Azure, HyperV and EC2 images are not compressed during imagefactory build. zip compressing the images so the image size will be comparable to other images.
@adahms It might affect documentation, so fyi...  This is upstream only change for now, and will go to Gaprindashvili and later branches.
> Compress Azure, HyperV and EC2 images

- kickstarts/partials/packages/includes.ks.erb
https://www.pivotaltracker.com/n/projects/1610127/stories/160659028
This PR is one of a set that will implement moving external authentication support from
the Apache module mod_auth_kerb to mod_auth_gssapi
Once all of the PRs are available I will remove the WIP flag
> Move from apache module mod_auth_kerb to mod_auth_gssapi

- scripts/git_checkout.rb
We're getting new git sha every time commit_sha is called. This causes appliance file names to be different for the same nightly build run if a commit happens when build is running:
manageiq-openstack-hammer-201810050800-1310fd6601.qc2
manageiq-ovirt-hammer-201810050800-28a765dd38.ova
This only affects file names and contents are ok as all kickstart files are generated at the same time.
Diff will be easier with [?w=1](https://github.com/ManageIQ/manageiq-appliance-build/pull/290/files?w=1)
> Set commit_sha just once

- kickstarts/base.ks.erb
- kickstarts/partials/post/python_modules.ks.erb
https://bugzilla.redhat.com/show_bug.cgi?id=1630801
Bambou (which is also listed in the BZ) is a dependency of vspk.
> Add vspk python module for Nuage

- CHANGELOG.md
> [Changelog] Add Sprint 97 and Hammer Beta1

- README.md
- scripts/Gemfile
- scripts/Gemfile.lock
- scripts/cli.rb
`Trollop` is a deprecated gem, and has been renamed/replaced by [`Optimist`](https://github.com/ManageIQ/optimist).
Since the changes made in this PR has no affect on the resulting appliance dependencies, this should be fine to be merged without needing to update other repos in the ManageIQ organization.
Links
-----
* Org search of current usage of old gem (hides some irrelevant repos):  [search](https://github.com/search?l=&q=Trollop+repo%3AManageIQ%2Fmanageiq+repo%3AManageIQ%2Fmanageiq-release+repo%3AManageIQ%2Fmanageiq-appliance_console+repo%3AManageIQ%2Fmanageiq-appliance-build+repo%3AManageIQ%2Fmanageiq-api+repo%3AManageIQ%2Fmanageiq-providers-vmware+repo%3AManageIQ%2Fhttpd_configmap_generator+repo%3AManageIQ%2Fguides&type=Code)
> Use Optimist

- kickstarts/partials/post/bundler.ks.erb
EPEL has updated qpid-proton-c to 0.26.0 recently. But this version doesn't seem to be compatible with gem version we lock to (0.22.0) and "bundle install" is currently failing for both `master` and `hammer` branches on appliances:
```
Installing qpid_proton 0.22.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
......
cproton.c: In function ‘_wrap_pn_selectables’:
cproton.c:16896:3: error: unknown type name ‘pn_selectables_t’
......
An error occurred while installing qpid_proton (0.22.0), and Bundler cannot continue.
```
To get back to working state quickly, temporarily downgrading the c library package to 0.19.0 that's available in ManageIQ copr repo and is known to work.
@Fryguy @carbonin please reivew
@gberginc @miha-plesko Just the other day, …
> Temporarily downgrade qpid proton c library

- kickstarts/partials/post/bundler.ks.erb
qpid_proton gem version is being updated to 0.26.0, so no need to downgrade c library package any more.
Reverting https://github.com/ManageIQ/manageiq-appliance-build/pull/307
Depends on https://github.com/ManageIQ/manageiq/pull/18544
> Remove temporary workaround to downgrade qpid-proton-c

- kickstarts/partials/packages/excludes.ks.erb
`dracut-network` package is being installed anyway as a dependency. Removing from the exclude file as having this can cause package conflict during install.
```
Mar 13 00:06:20 localhost packaging[1213]: deselect package dracut-network
...
Mar 13 00:06:23 localhost yum[1213]: TSINFO: Marking dracut-network-033-554.el7.x86_64 as install for kexec-tools-2.0.15-21.el7.x86_64
...
Mar 13 00:11:02 localhost packaging[1213]: Installing dracut-network (451/665)
```
> Don't exclude dracut-network package

- kickstarts/partials/packages/excludes.ks.erb
We're currently excluding `*-firmware` packages. But `linux-firmware` is required by kernel and installed. Instead of excluding `*-firmware`, excluding all firmware that's not `linux-firmware` to avoid possible package conflict during install.
```
Mar 11 21:41:09 localhost packaging[1202]: deselect package *-firmware
...
Mar 11 21:41:14 localhost yum[1202]: TSINFO: Marking linux-firmware-20180911-69.git85c5d90.el7.noarch
as install for kernel-3.10.0-957.5.1.el7.x86_64
```
Verified only `linux-firmware` is present on the machine by running a build with this change.
> Exclude specific -firmware packages only

- kickstarts/partials/post/ruby_install.ks.erb
2.4.6 includes multiple CVE fixes:
https://www.ruby-lang.org/en/news/2019/03/05/multiple-vulnerabilities-in-rubygems/
This is `hammer` only change, as I will be updating `master` to 2.5.x
> [HAMMER] Update to ruby 2.4.6

- kickstarts/partials/packages/includes.ks.erb
- kickstarts/partials/post/firewalld.ks.erb
- kickstarts/partials/post/systemd.ks.erb
This should replace a good amount of the system management
we do in the appliance console
Requires https://github.com/ManageIQ/manageiq-appliance/pull/239 for cockpit to work
> Add cockpit packages and changes to allow it to run by default

- kickstarts/partials/main/disk_layout.ks.erb
Starting with RHEL6 the mount option nobarrier was no longer recommended.
Starting with RHEL8 the mount option nobarrier was no longer supported. The mount
command fails on RHEL8 if the nobarrier option is provided.
This PR removes the unrecommended nobarrier mount option.
This will be more important once we can build upstream against a CentOS version 8.
> Do not use unrecommended mount option nobarrier

- config/base.json.azure
- scripts/vmbuild.rb
Compiling assets can fail on Azure, running out of memory during build. While I investigate the permanent fix, putting a temporary fix to increase libvirt memory.
> Temporary fix for asset compile error on Azure

- config/base.json
2GB just isn't enough... compiling assets could take up to 4GB at times.
> Increase libvirt memory to 4GB to reduce build time

- kickstarts/partials/packages/includes.ks.erb
- kickstarts/partials/post/python_modules.ks.erb
We install these into a new venv so that we don't conflict with
appliance python packages.
This list is taken directly from
https://raw.githubusercontent.com/ansible/awx/c7bb0f10e10476e10df8a7e7b26732eb60958ca1/requirements/requirements_ansible.txt
which is the result of resolving the dependencies from
https://github.com/ansible/awx/blob/c7bb0f10e10476e10df8a7e7b26732eb60958ca1/requirements/requirements_ansible.in
I feel like taking the resolved file first is safer since pip doesn't
do true dependency resolution (pypa/pip#988)
Replacement for https://github.com/ManageIQ/manageiq-appliance-build/pull/340
Looking for input on places to put the list of packages. I felt like people wouldn't go looking for this list in `manageiq-appliance`, but it needs to live on disk somewhere ...
I could …
> Install python modules required for embedded ansible credentials

- kickstarts/partials/post/ui_compile.ks.erb
As a part of ui-service build, we need to run
`yarn available-languages`
That command will update list of available languages and put them into `available_languages.json` file. That json file determines which language choices will be presented to the user during login.
The reason we need it in the build process is that there's a mechanism for restricting the list of presented languages to the user by creating a file `supported_languages.json`. When this file exists, `yarn available-languages` includes only languages that are explicitly specified in the supported list.
We do have `supported_languages.json` in CFME build, but currently that list is not being applied, because we lack this one step in the build process.
https://bugzilla.redhat.com/show_bug.cgi?id=1743734
@miq-bot add_label …
> Add yarn available-languages to ui-service build

- kickstarts/partials/post/ui_compile.ks.erb
Add an option to override npm registry. This will be no-op if npm_registry/npm_registry_cleanup don't exist on the build machine.
Example npm_registry.erb.ks
```
yarn config set registry <your registry>
find ${repos_root} -name yarn.lock -exec sed -i 's|https://registry.yarnpkg.com|<your registry>|g' {} +
find $(gem env gemdir)/bundler -name yarn.lock -exec sed -i 's|https://registry.yarnpkg.com|<your registry>|g' {} +
```
This will cover `yarn install` which is what our UI uses and takes care of all packages except for `yarn`. I will create a follow up PR for `npm install` which will take care of `yarn`.
> Add option to use a different npm registry for yarn

- kickstarts/partials/post/gce.ks.erb
Currently the build isn't installing packages needed for Google Compute Engine (which prevents users from ssh'ing to the machine) due to errors:
```
yum install -y google-compute-engine google-compute-engine-init google-config
...
Transaction check error:
file /etc/dhcp/dhclient.d/google_hostname.sh conflicts between attempted installs of google-compute-engine-1:20190801.00-g1.el7.noarch and google-config-2.1.2-0.1484936429.el7.x86_64
file /etc/rsyslog.d/90-google.conf conflicts between attempted installs of google-compute-engine-1:20190801.00-g1.el7.noarch and google-config-2.1.2-0.1484936429.el7.x86_64
file /etc/sysctl.d/11-gce-network-security.conf conflicts between attempted installs of google-compute-engine-1:20190801.00-g1.el7.noarch and google-config-2.1.2-0.1484936429.el7.x86_64 …
```
> Update Google Compute Engine packages

- kickstarts/partials/post/ui_compile.ks.erb
- scripts/kickstart_generator.rb
https://github.com/ManageIQ/manageiq-appliance-build/pull/345 worked only partially - when `--local` is used and when `bin/kickstart_build.rb` is used. For nightly build, manageiq-appliance-build is cloned to a different directory and kickstart files from there are used. Since `@build_base` is different in those cases, my previous PR didn't work.
I'm changing to take optional kickstart partials from a different location. Settings like npm registry will be per build machine setting, not per build/branch setting, so it actually makes sense the files live somewhere else that all builds can access.
For the new `render_partial_if_exist` method, use of `Productization.file_for` isn't needed as we can commit all files for downstream builds and this new method won't be used there.
Also added …
> Fix optional kickstart partial handling and add support for "npm install"

- kickstarts/base.ks.erb
- kickstarts/partials/post/systemd.ks.erb
- Ensure network service is enabled
- Remove invalid configurations for adapters en*
- Add a config for eth0
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1755398
> Configure network adapters during kickstart

- scripts/Gemfile
Updated our build machine for https://github.com/ManageIQ/manageiq-appliance-build/pull/352 and noticed activesupport isn't there, so adding to Gemfile.
> Add activesupport to Gemfile

- scripts/target.rb
- scripts/vmbuild.rb
We started creating 2 formats for oVirt (ova and qcow2) in https://github.com/ManageIQ/manageiq-appliance-build/pull/193 because oVirt 3.x supported ova only and 4.1 supported qcow2 only.
The currently supported versions of oVirt (4.x) all support qcow2, so we no longer need to build 2 different formats.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1740898
> Drop OVA for oVirt

- kickstarts/partials/post/ui_compile.ks.erb
Nightly builds are failing to build SUI
```
+ [21:12:44] pushd /opt/manageiq/manageiq-ui-service
/opt/manageiq/manageiq-ui-service /
+ [21:12:44] yarn install
yarn install v1.19.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error Incorrect integrity when fetching from the cache
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
To workaround this issue (https://github.com/yarnpkg/yarn/issues/7584), cleaning yarn cache after OpsUI build so I don't need to hardcode to yarn 1.18.
> Clean yarn cache after OpsUI build

- config/base.json
- config/base.json.azure
- scripts/vmbuild.rb
Bump to 8GB memory and 4 CPUs. Also... since we're bumping, we no longer need to have a separate file for Azure.
> Bump resources for oz

- bin/shared_functions.sh
We check for running build before starting another, but...
1. This prevents running nightly from other branches, so we can't run nightly for `master` and `ivanchuk` at the same time, which we need to do. 
1. Depending on what's being processed at the time this check happens, it might kick off another nightly anyway. We check if `virsh list` returns domains to determine if another build is running, but a virsh domain doesn't exist throughout the entire build process but exists only when certain things are processed.
So... changing to check if vmbuild.rb from the same directory is already running.
example ps output:
root      27875      1  0 Oct10 ?        00:00:00 time ruby /build/manageiq-appliance-build/bin/../scripts/vmbuild.rb --type nightly --upload --reference master --copy-dir …
> Change how to identify running build

- kickstarts/partials/post/ui_compile.ks.erb
yarn 1.19.1 fixed the issue that we needed this workaround for.
> Remove 'yarn cache clean' workaround

- README.md
- kickstarts/partials/post/npm_registry_setup.ks.erb
- kickstarts/partials/post/npm_yarn_registry_cleanup.ks.erb
- kickstarts/partials/post/ui_compile.ks.erb
- kickstarts/partials/post/yarn_registry_setup.ks.erb
Overriding npm/yarn registry is currently being done by having optional kickstart files on the build machine. Changing to use environment variables so the files can be committed to this repo and maintained properly, rather than being reviewed offline... 
Took the files we're currently using to generate our nightly builds, then changed to use environment variables.
Note: As a part of build optimization work, yarn.lock handling will be modified in upcoming PR.
> Use ENV variables for optional npm/yarn registry override

- kickstarts/partials/post/npm_yarn_registry_cleanup.ks.erb
- kickstarts/partials/post/ui_compile.ks.erb
- kickstarts/partials/post/yarn_registry_setup.ks.erb
To reduce appliance build time and final image size, changed to use tmpfs for node_modules and yarn cache.
The build time for %post section was reduced from 50min~1 hour to 40min or so. The compressed image size for vSphere went down from 2.3GB to 1.9GB.
Also since node_modules will no longer be on the appliance, yarn.lock will be left on the machine even when NPM_REGISTRY_RESET is used (but lock file will point to the yarn default registry).
Thanks for the idea @himdel 
cc @martinpovolny @bdunne @Fryguy
> Use tmpfs for node_modules and yarn cache

- kickstarts/base.ks.erb
- kickstarts/partials/main/repos.ks.erb
- kickstarts/partials/packages/includes.ks.erb
- No need to install documentation
- Remove packages installed by default but not needed (`linux-firmware` and `doxygen`)
- Remove `docker` as it's no longer needed
- Remove unused postmodern/ruby-install repo (ruby-install comes from ManageIQ-Master)
> Cleanup package installation

- kickstarts/partials/post/bundler.ks.erb
```
BEFORE ANYTHING...
[root@dhcp-8-99-141 ~]# df -h
Filesystem                              Size  Used Avail Use% Mounted on
devtmpfs                                2.9G     0  2.9G   0% /dev
tmpfs                                   2.9G   52K  2.9G   1% /dev/shm
tmpfs                                   2.9G  904K  2.9G   1% /run
tmpfs                                   2.9G     0  2.9G   0% /sys/fs/cgroup
/dev/mapper/vg_system-lv_os              11G  3.6G  7.0G  34% /
/dev/sda1                              1014M  153M  862M  15% /boot
/dev/mapper/vg_system-lv_home          1014M   33M  982M   4% /home
/dev/mapper/vg_system-lv_tmp           1014M   33M  982M   4% /tmp
/dev/mapper/vg_system-lv_var             12G  926M   12G   8% /var
/dev/mapper/vg_system-lv_var_log         11G   55M   11G …
```
> Clean up extra space used by gems and bundler

- README.md
- bin/container-build.sh
- bin/nightly-build.sh
- bin/release-build.sh
The new script will build pod images, followed by monolithic image, and push the images.
Since builds for 2 different branches might run at the same time, sources for container images will be cloned to branch specific directories (just like manageiq-appliance-build)
`podman` comes with CentOS 8, but the version of podman on CentOS 8.0 had a few issues, so using `docker-ce` for now. Will revisit when CentOS 8.1 is released (at least 1 issue will be fixed in that version).
cc @carbonin
> Build container images in nightly/release build

- kickstarts/partials/post/python_modules.ks.erb
Virtualenv 20.0.0+ (released Feb 10) is causing error setting up virtualenv on our appliances (probably because of python 2.7...)
```
+ [21:41:14] virtualenv venv
Traceback (most recent call last):
File "/usr/bin/virtualenv", line 7, in <module>
from virtualenv.__main__ import run_with_catch
File "/usr/lib/python2.7/site-packages/virtualenv/__init__.py", line 3, in <module>
from .run import cli_run
File "/usr/lib/python2.7/site-packages/virtualenv/run/__init__.py", line 9, in <module>
from .plugin.activators import ActivationSelector
File "/usr/lib/python2.7/site-packages/virtualenv/run/plugin/activators.py", line 6, in <module>
from .base import ComponentBuilder
File "/usr/lib/python2.7/site-packages/virtualenv/run/plugin/base.py", line 9, in <module>
from importlib_metadata import …
```
> Use virtualenv 16.7.9

- config/base.tdl
- config/base_azure.tdl
- kickstarts/base.ks.erb
- kickstarts/partials/main/network.ks.erb
- kickstarts/partials/main/repos.ks.erb
- kickstarts/partials/packages/includes.ks.erb
- kickstarts/partials/post/bundler.ks.erb
- kickstarts/partials/post/ovirt_ansible.ks.erb
- kickstarts/partials/post/python_modules.ks.erb
- kickstarts/partials/post/repos.ks.erb
- kickstarts/partials/post/ruby_install.ks.erb
- kickstarts/partials/post/systemd.ks.erb
- scripts/vmbuild.rb
Various changes to update our appliances to be CentOS 8 based. A few things to note...
- Not all ovirt-ansible-* packages are available for CentOS 8 and this causes none of the ovirt-ansible-* packages to be installed (due to missing dependency).
- Updated to nodejs 12 as that's the latest LTS release and is available in AppStream cc @himdel
- Due to CentOS 8 not having libssh2-devel (which is needed for rugged gem ssh support), RPMs were built in copr and are installed in %post section. Trying to install in %package fails due to conflicts.
Follow up in separate PRs:
- Change to use ruby from AppStream, rather than using ruby-install. Some extra change will be needed to make this work.
- We should probably update ruby version.
@jrafanie I'll ping you on those 2 items above.
- Change OS …
> CentOS 8 based appliance

- scripts/cli.rb
- scripts/spec/cli_spec.rb
- scripts/spec/target_spec.rb
- scripts/spec/uploader_spec.rb
- scripts/target.rb
- scripts/uploader.rb
- scripts/vmbuild.rb
v2v-conversion-host appliance is different from the rest of appliances we build, where kickstart file comes from a different repo and the final appliance file name has different format.
For now, I've opted to handle those differences using `if target == "v2v"`. If we ever need to create another non-ManageIQ appliance, I'll look into either adding new options in Build::Target or re-organizing vmbuild.rb so target specific `if` can be removed.
Requires https://github.com/ManageIQ/manageiq-appliance-build/pull/383
> Build v2v-conversion-host appliance 

- scripts/uploader.rb
In https://github.com/ManageIQ/manageiq-appliance-build/pull/385, I missed one place where date parsing needed to be updated. Changed to use the similar regex as generating filenames.
> Fix date parsing to account for v2v appliance

- scripts/target.rb
As per request... virt-v2v requires more space than what's currently available, so increasing disk size to 20GB.
cc @fdupont-redhat
> Increase v2_conv_host appliance to 20GB

- kickstarts/partials/main/repos.ks.erb
All packages can now come from epel and/or other repos already defined and no need to use playground any more.  epel is more stable than playground and preferred.
> Replace playground repo with epel

- kickstarts/partials/packages/includes.ks.erb
- kickstarts/partials/post/bundler.ks.erb
CentOS 8 repo no longer contains libssh2 rpm and installing from ManageIQ copr repo won't conflict, so removing the workaround.
> Remove libssh2 workaround

- kickstarts/partials/post/bundler.ks.erb
- Updated path to rugged, as it's no longer a git based gem
- manageiq-smartstate gem no longer contains "Packages" file
> Update gem clean up

- kickstarts/partials/post/bundler.ks.erb
Related to https://github.com/ManageIQ/manageiq/pull/19874
Also changed to use `bundle config set` rather than `--with` due to deprecation warning:
[DEPRECATED] The `--with` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set with 'qpid_proton'`, and stop using this flag
> Bundle with 'systemd' optional group

- README.md
Add documentation step to download and place centos 8 iso.
This includes an example link that is current but that link will change with each release of centos 8. I am not sure if there is a way to link to the latest version directly.
Issue: https://github.com/ManageIQ/manageiq-appliance-build/issues/398
> Add centos 8 download doc

- scripts/uploader.rb
```
/usr/share/ruby/psych.rb:497:in `initialize': No such file or directory @ rb_sysopen - /build/manageiq-appliance-build/scripts/../config/upload.yml (Errno::ENOENT)
from /usr/share/ruby/psych.rb:497:in `open'
from /usr/share/ruby/psych.rb:497:in `load_file'
from /build/manageiq-appliance-build/scripts/uploader.rb:87:in `config'
from /build/manageiq-appliance-build/scripts/uploader.rb:97:in `login'
from /build/manageiq-appliance-build/scripts/uploader.rb:23:in `run'
from /build/manageiq-appliance-build/scripts/uploader.rb:13:in `upload'
from /build/manageiq-appliance-build/bin/../scripts/vmbuild.rb:248:in `<main>'
```
> Don't error when upload is called without upload.yml

- kickstarts/partials/main/repos.ks.erb
- kickstarts/partials/post/repos.ks.erb
Disallow installing qpid-proton from epel repo (so it will come from ManageIQ copr repo), to ensure the version matches with the gem version.
Related to: https://github.com/ManageIQ/manageiq/issues/19942 and https://github.com/ManageIQ/manageiq/pull/20016
Building 0.30.0 rpm in ManageIQ-Master and ManageIQ-Jansa copr repo now.  Until https://github.com/ManageIQ/manageiq/pull/20016 is merged, bundle will fail on master/jansa appliances with or without this PR.
> Control qpid-proton rpm version by installing from ManageIQ copr repo

- kickstarts/partials/main/repos.ks.erb
- kickstarts/partials/post/repos.ks.erb
Backport of https://github.com/ManageIQ/manageiq-appliance-build/pull/409 as yum command is slightly different.
Since qpid_proton gem 0.26.0 was being used with 0.29.0 rpm without any problem, kicked off 0.29.0 rpm build in ManageIQ-Ivanchuk copr repo.
EPEL was updated to 0.30.0 rpm 2-3 weeks ago, and `bundle install` is failing since.
> [IVANCHUK] Control qpid-proton rpm version by installing from ManageIQ copr repo 

- scripts/uploader.rb
In order to enable migrating to a new CDN
- Refactored the code to split the Rackspace specifics out of the common methods
- Added a DigitalOcean uploader
Once this is running and new builds are being uploaded to both destinations, I will script back-filling all of the existing images.  When the switch to DigitalOcean Spaces is complete I will remove the Rackspace calls.
> Upload to multiple destinations

- kickstarts/partials/main/repos.ks.erb
- kickstarts/partials/post/ovirt_ansible.ks.erb
With the revert of IMS 1.3 changes, we need to downgrade v2v-conversion-host as well. The needed version is provided by oVirt 4.4, which went GA last week.
Related PR: https://github.com/ManageIQ/manageiq/pull/20168
> Update to oVirt 4.4 GA

- .gitignore
- bin/nightly-build.sh
- bin/release-build.sh
- bin/rpm-build.sh
Once we go RPM based, majority of the code will come from RPMs and there is very little left outside of it. So I made appliance/container build not to start if RPM build wasn't successful. I think this is less confusing than having an appliance build with RPMs from the day before.
Copr token and options.yml need to be setup on the build machine.
TODOs (follow up PRs)
- Clean up options/code no longer used
- Add support for "local" build - with this PR, you will not be able to use non-default repo/branches for nightly/release build, unless you add manual steps to build own RPMs, then change yum repo.
Related PR: https://github.com/ManageIQ/manageiq-appliance-build/pull/415
> Add building RPMs before starting appliance build

- bin/kickstart_build.rb
- kickstarts/partials/main/repos.ks.erb
- kickstarts/partials/post/repos.ks.erb
- scripts/kickstart_generator.rb
- scripts/spec/kickstart_generator_spec.rb
- scripts/vmbuild.rb
With this change, nightly appliance will have nightly yum repo enabled by default, allowing `yum update` to pick up the latest manageiq-* RPMs from nightly/release repos.
The release appliances will continue to only have release repo enabled by default and the users are expected to enable nightly repo to update to a nightly build.
> Add nightly yum repo only for non-release build

- kickstarts/base.ks.erb
- kickstarts/partials/post/ovirt_ansible.ks.erb
- kickstarts/partials/post/repos.ks.erb
A part of https://github.com/ManageIQ/manageiq-appliance-build/issues/422
Requires https://github.com/ManageIQ/manageiq-rpm_build/pull/58 (and new rpm build with this change)
> Move ovirt-ansible-roles to manageiq-gemset requires

- kickstarts/partials/post/python_modules.ks.erb
Reference https://github.com/ManageIQ/manageiq-rpm_build/issues/43
> additional dependencies needed for installing python modules on ppc64le

- config/base.json
Now that a lot of the resource intensive work is moved out to rpm build, we can reduce the CPU/Memory settings.
Ran vmware and azure builds to verify build still works with this change.
> Lower CPU and Memory

- kickstarts/base.ks.erb
Some post processing tasks need network and replacing ifcfg-en* with ifcfg-eth0 too early causes an error. Moving that step to be the last step in %post section.
The error was noticed in azure image build as waagent deprovision process failed:
```
14:23:51,574 INFO anaconda:program: + [10:20:50] waagent -force -deprovision
...
14:23:51,574 INFO anaconda:program: 2020/08/19 10:20:51.513141 INFO Examine /proc/net/route for primary interface
14:23:51,574 INFO anaconda:program: 2020/08/19 10:20:51.523703 INFO Primary interface is [ens3]
14:23:51,575 INFO anaconda:program: 2020/08/19 10:20:51.541999 ERROR Failed to run 'deprovision': Traceback (most recent call last):
...
14:23:51,582 INFO anaconda:program: FileNotFoundError: [Errno 2] No such file or directory: …
```
> Change ifcfg-en* to eth0 after all post processing tasks are completed

- bin/container-build.sh
- bin/nightly-build.sh
- bin/release-build.sh
Also changed to use getopts and removed environment variables (MIQ_REF, SUI_REF and APPLIANCE_REF) that are no longer used.
Requires https://github.com/ManageIQ/manageiq-pods/pull/597
> Add build type (release or nightly) support to container build

- kickstarts/partials/post/python_modules.ks.erb
Currently, setting up ansible venv is failing:
```
Running setup.py install for pycurl: started
Running setup.py install for pycurl: finished with status 'error'
....
src/pycurl.h:174:13: fatal error: openssl/ssl.h: No such file or directory
^~~~~~~~~~~~~~~
```
Looks like a newer version of pycurl (7.43.0.6) requires openssl-devel now. But what's required in venv is `Collecting pycurl>=7.19.0` and we already have `python3-pycurl-7.43.0.2-4.el8.x86_64` installed.  There are more packages like that where we already have the needed version installed by rpm but we're trying to pip install in venv again.
So I'm adding the flag to allow venv to be able to access system packages to eliminate duplicates and avoid running into errors like this.
> Allow ansible venv to access system packages

- kickstarts/partials/post/python_modules.ks.erb
Goes with https://github.com/ManageIQ/manageiq-rpm_build/pull/93 ~~and https://github.com/ManageIQ/manageiq-pods/pull/632~~
> Move vspk/pylxca python module installation to rpm requires

- kickstarts/base.ks.erb
Remove machine iD from the images so it will be generated during boot.
https://bugzilla.redhat.com/show_bug.cgi?id=1889302
> Remove machine-id

- bin/kickstart_build.rb
- kickstarts/partials/main/repos.ks.erb
- kickstarts/partials/packages/includes.ks.erb
- kickstarts/partials/post/repos.ks.erb
- scripts/.gitignore
- scripts/cli.rb
- scripts/kickstart_generator.rb
- scripts/productization.rb
- scripts/spec/cli_spec.rb
- scripts/spec/kickstart_generator_spec.rb
- scripts/spec/productization_spec.rb
- scripts/vmbuild.rb
@simaishi Please review
This PR adds
- the ability to pass the product name which is used to determine the rpm names as well as the built appliance name.
- the ability to specify extra repos via the productization directory under `main/repos-extra.ks.erb` and optionally `post/repos-extra.ks.erb`  (which is used when the rpm names are available elsewhere)
cc @bennett-white
> Allow for productization of build

- kickstarts/partials/main/repos.ks.erb
In CentOS 8.3, yum repo name changed:
BaseOS -> baseos
AppStream -> appstream
Updating to match the new names, so rpm/repo manifest will use the same name.
> Update yum repo name to match what's used in CentOS 8.3

- kickstarts/partials/post/bundler.ks.erb
The latest version of bundler (2.2.4) doesn't work with the version of git available on CentOS 7. It's probably not a good idea to keep updating bundler on older branches anyway, so locking to 2.1.4 which is what was used in ivanchuk-7 release.
PR for podified build: https://github.com/ManageIQ/manageiq-pods/pull/667
> [IVANCHUK] Lock bundler to v2.1.4

- scripts/cli.rb
- scripts/spec/uploader_spec.rb
- scripts/uploader.rb
- scripts/vmbuild.rb
This is useful when running builds on an off-premise machine as artifacts are no longer needed on the machine once uploaded.
Need #457 to actually make a use of this in nightly builds.
> Add an option to delete artifacts after upload

- bin/nightly-build.sh
- bin/release-build.sh
Currently, nightly script can only take 1 build option (either `fileshare`, `no-fileshare` or `local`) plus an option to run in foregrond, and release build can only take tag as argument.
Changing the scripts to take any build arguments, and that will:
* fix the issue where you can't use fileshare/non-fileshare and local at the same time for nightly build
* allow passing existing argments like product name
* not require modifying the scripts when new options get added
> Allow passing any build arguments to nightly/release scripts

- bin/rpm-build.sh
Add :Z on the volume mounts to allow access to the container.  Without this, the RPM build errors while trying to access the options file
> In CentOS8, docker points to podman and containers don't run as root

- kickstarts/partials/post/appliance_init.ks.erb
Fixes https://github.com/ManageIQ/manageiq-appliance-build/issues/454
This PR adds starting the kafka server and it renames the db_init.ks.erb to appliance_init.ks.erb since it will be used to initialize more than just the db.
> Add starting the kafka server to the kickstart

- kickstarts/base.ks.erb
Fixes:
```
/build/manageiq-appliance-build/scripts/kickstart_generator.rb:50:in `render': partial file "post/db_init" not found (ArgumentError)
from /build/manageiq-appliance-build/scripts/kickstart_generator.rb:64:in `render_partial'
from (erb):86:in `render'
from /usr/share/ruby/erb.rb:876:in `eval'
from /usr/share/ruby/erb.rb:876:in `result'
from /build/manageiq-appliance-build/scripts/kickstart_generator.rb:56:in `render'
from /build/manageiq-appliance-build/scripts/kickstart_generator.rb:60:in `evaluate_erb'
from /build/manageiq-appliance-build/scripts/kickstart_generator.rb:31:in `block in run'
from /build/manageiq-appliance-build/scripts/kickstart_generator.rb:28:in `each'
from /build/manageiq-appliance-build/scripts/kickstart_generator.rb:28:in `run'
from …
```
> This file was renamed in #470

- bin/release-build.sh
Currently:
```
[root@build-lasker manageiq-appliance-build]# /build/manageiq-appliance-build/bin/release-build.sh lasker-1-beta1
lasker-1-beta1 release build kicked off, see logs @ /build/logs/lasker-1-beta1*.log ...
```
But in the log directory:
```
-rw-r--r--.  1 root root   135657 Apr 20 17:28 _rpm.log
```
> Fix log file names for release build script

- kickstarts/base.ks.erb
For some reason we're getting an up to date manageiq-appliance RPM but other manageiq-* RPMs are at older versions.  Force them to be updated to the latest available version.
> Ensure manageiq packages are up to date

- kickstarts/partials/post/systemd.ks.erb
evm-watchdog was removed and replaced with a standard Restart=on-failure for evmserverd and manageiq-db-ready
https://github.com/ManageIQ/manageiq-appliance/pull/327
> Don't systemctl enable evm-watchdog

- kickstarts/partials/post/systemd.ks.erb
We're removing it in https://github.com/ManageIQ/manageiq-rpm_build/pull/202
People should use a real mail server, not a mail server hosted on our appliances.
> Don't enable postfix in the kickstart

- kickstarts/partials/packages/excludes.ks.erb
kafka requires jre 1.8
jre 1.8 requires libasound.so.2 which is provided by alsa-lib
```
19:46:14,279 WARNING anaconda:packaging:
Problem: conflicting requests
- package manageiq-appliance-14.0.0-20210908000050.el8.x86_64 requires kafka, but none of the providers can be installed
- package manageiq-appliance-14.0.0-20210909000027.el8.x86_64 requires kafka, but none of the providers can be installed
- package manageiq-appliance-14.0.0-20210909150854.el8.x86_64 requires kafka, but none of the providers can be installed
- package manageiq-appliance-14.0.0-20210910184617.el8.x86_64 requires kafka, but none of the providers can be installed
- package manageiq-appliance-14.0.0-20210910205409.el8.x86_64 requires kafka, but none of the providers can be installed
- package …
```
> Don't exclude alsa, it's causing appliance image builds to fail

- kickstarts/partials/main/repos.ks.erb
- lib/tasks/release.rake
This change is similar to the one in https://github.com/ManageIQ/manageiq-rpm_build/pull/223.
While this doesn't actually break the build, it is inaccurate.
Note that 0b5ca2a9ddad4e5eb2686a4ba2587daeca7dcf12 will be forward-ported to master via cherry-pick after this is merged.
> [MORPHY] Fix issue where the new branch might not have the updated repos

- config/base.json
- kickstarts/base.ks.erb
- Remove deprecated `install` command
- Increase installer RAM to get around issues before RPM installation
> Installer issues

- bin/iso_modify.sh
Secrets in the kickstart config were being saved to the appliance
This script will extract the ISO, add the `inst.nosave=all` kernel parameter, rebuild the ISO and clean up.  Please run this script against any source ISO that will be used for builds with secrets in the kickstart.
Note: This does not protect us from exposing any secrets in the post-install script
https://access.redhat.com/solutions/2740121
> Add kernel parameter to prevent saving kickstart config

- README.md
This is required since we switched to CentOS Stream 8
> Document adding -joliet-long option to genisoimage

- README.md
- kickstarts/centos8_build_machine.ks
- kickstarts/partials/main/repos.ks.erb
Manual backport of #481
While the CentOS 8 repos are still available, CentOS 8 is EOL and we've already switched to using the Stream ISO.
Specifically, the latest version of postgresql-server available in the old repo is 10.17 and the stream repo contains 10.19.
> [MORPHY] Move to CentOS Stream

- bin/iso_modify.sh
- config/base.tdl.erb
- scripts/vmbuild.rb
~~Expected usage is that if someone doesn't want kickstart logging, they can pass `--no-ks-log` to vmbuild~~
~~I intentionally made the iso_modified.sh a shell script to mirror iso_modify.sh.  That way after someone manually changes it with iso_modify.sh, they can check it with iso_modified.sh in a similar way.~~
As dicsussed, I've changed the iso_modify.sh to first check if modified, and then we just always call it from the build.  Specific modifications can be opted out with ENV vars.
> Add ability to inspect the ISO for kickstart logging

- kickstarts/base.ks.erb
As of https://github.com/ManageIQ/manageiq-rpm_build/pull/282 and
https://github.com/ManageIQ/manageiq-ui-classic/pull/8320
nodejs is a build time dependency to build the rpms and minify the assets but is
not needed a runtime.
For https://github.com/ManageIQ/manageiq-ui-classic/issues/8300
NOTE: See https://github.com/ManageIQ/manageiq-ui-classic/issues/8300 for the breakdown of required PRs.
> Nodejs is no longer a runtime dependency

- kickstarts/base.ks.erb
- kickstarts/partials/main/db_fs.ks.erb
- kickstarts/partials/post/appliance_init.ks.erb
- scripts/spec/target_spec.rb
- scripts/target.rb
For demo purposes it is nice to have an appliance which automatically initializes itself on boot, but this makes it quite difficult to use these images in a production deployment which requires multiple appliances.
This removes the auto-initialization on first-boot allowing the user to use appliance_console to connect the appliance to an existing region or create a new one.
Follow-up:
* Remove `manageiq-initialize.service` from manageiq-appliance - https://github.com/ManageIQ/manageiq-appliance/pull/359
* Document configuring kafka - https://github.com/ManageIQ/manageiq-documentation/pull/1675
* Reduce the root disk size for the image builds
> Don't automatically initialize appliances

- kickstarts/partials/post/python_modules.ks.erb
Newer builds install python 3.8 and ansible itself uses python 3.8.  As
such, we need the dependencies installed into there, matching the required
version.
Part of https://github.com/ManageIQ/manageiq/issues/22009
@agrare Please review.
> Move manageiq venv to python 3.8 

- kickstarts/partials/post/python_modules.ks.erb
- Bump pygments to 2.7.4 for CVE-2021-20270 and CVE-2021-27291
- Bump urllib3 to 1.26.5 for CVE-2021-33503
- This required bumping requests to 2.25.1
- Bump lxml to 4.9.1 for CVE-2018-19787, CVE-2020-27783, CVE-2021-28957,
CVE-2021-43818, and CVE-2022-2309
- Bump jinja2 to 2.11.3 for CVE-2020-28493
- Bump paramiko to 2.10.1 for CVE-2022-24302
Also be more explicit for PyYAML to match the installed package
@agrare Please review.  I verified with the vsphere.yml and the hello_world.yml on the docker images
> Update certain python dependencies for CVEs

- kickstarts/partials/post/python_modules.ks.erb
The packages in this commit will still be installed, but we let pip do the resolutions.  This will keep those packages up to date.
The following is a diff showing before/after of what's installed:
```diff
@@ -1,14 +1,15 @@
-adal==1.2.1
+adal==1.2.7
ansible==5.4.0
ansible-core==2.12.7
apache-libcloud==2.5.0
-appdirs==1.4.3
-applicationinsights==0.11.1
-argcomplete==1.9.4
+appdirs==1.4.4
+applicationinsights==0.11.10
+argcomplete==2.0.0
asn1crypto==0.24.0
azure-cli-core==2.0.35
-azure-cli-nspkg==3.0.2
-azure-common==1.1.11
+azure-cli-nspkg==3.0.4
+azure-common==1.1.28
+azure-core==1.25.1
azure-graphrbac==0.40.0
azure-keyvault==1.0.0a1
azure-mgmt-authorization==0.51.1
@@ -36,73 +37,73 @@ azure-mgmt-sql==0.10.0
azure-mgmt-storage==3.1.0
azure-mgmt-trafficmanager==0.50.0
azure-mgmt-web==0.41.0 …
```
> Remove transitive dependencies from the list of python packages

- kickstarts/base.ks.erb
~~Depends on ruby 3 support from https://github.com/ManageIQ/manageiq/pull/21531~~ MERGED 🎉 
Depends on https://github.com/ManageIQ/manageiq-rpm_build/pull/304 for ruby 3 rpm builds
> Update appliances to use ruby 3

- kickstarts/base.ks.erb
Similar change to https://github.com/ManageIQ/manageiq-pods/pull/846
@agrare Please review.  I'm not sure this will actually fix the python 3.9 issue, but we can see after build.
> Avoid installing weak dependencies

- kickstarts/partials/packages/excludes.ks.erb
epel-next-release can prematurely bring in newer versions of packages we aren't prepared for, so exclude it.
@agrare Please review.
> Exclude epel-next-release rpm from being installed

- kickstarts/partials/post/python_modules.ks.erb
I'm not comfortable backporting https://github.com/ManageIQ/manageiq-appliance-build/pull/523 just yet, so this is a selective update of oauthlib to drop CVE-2022-36087
> [OPARIN] Bump oauthlib to 3.2.1 for CVE-2022-36087

- config/base.json
In testing, I used 10GB and still used some swap.  This should give a little bit of ead room and avoid the "OSError: Cannot allocate memory" issues.
> Bump up to 12GB RAM

- config/base.json
We are hitting memory issues on the build machine where it tries to run multiple builds at the same time, but it can not allocate memory because the host system is out of memory.  In a few test installations, I was able to run an install with the current kickstart and the guest would go slightly into swap during package installation, but the install completed successfully and speed was not significantly different.
Error:
```
2023-03-20 05:43:35,280 ERROR imgfac.Builder.Builder thread(880bbd37) Message: Exception encountered in _build_image_from_template thread 2023-03-20 05:43:35,280 ERROR imgfac.Builder.Builder thread(880bbd37) Message: internal error: process exited while connecting to monitor: 2023-03-20T09:43:33.265855Z qemu-kvm: cannot set up guest memory 'pc.ram': Cannot allocate …
```
> Drop build memory back to 4GB

- kickstarts/base.ks.erb
https://docs.centos.org/en-US/8-docs/advanced-install/assembly_kickstart-commands-and-options-reference/#auth-or-authconfig-deprecated_kickstart-commands-for-system-configuration
In https://www.mankier.com/7/authselect-migration there's a note that says:
Authconfig options --enableshadow and --passalgo=sha512 were often used to make sure that passwords are stored in /etc/shadow using sha512 algorithm. The authselect profiles now use the yescrypt hashing method and it cannot be changed through an option (only by creating a custom profile). You can just omit these options.
> authconfig is deprecated in favor of authselect

- bin/clean_dead_factory_build_vms.sh
If something goes wrong in the VM build process, ImageFactory will give up after 7200 seconds.  It doesn't clean up that VM, it just takes a screenshot. If too mnay running VMs are left around it causes problems for new builds since the host can run out of memory.
CPU time is not perfect, but it should be good enough.
> Add a script that can be run by cron to clean up factory build vms

- scripts/vmbuild.rb
The JSON.load_file method is not present is the version of the JSON gem that comes with Ruby 2.7.
@jrafanie Please review
cc @bdunne
> Fix issue when newer json gem is not present

- bin/rpm-build.sh
`Error: short-name resolution enforced but cannot prompt without a TTY`
> Fully qualify the docker image

- kickstarts/partials/main/repos.ks.erb
- kickstarts/partials/post/repos.ks.erb
Undo https://github.com/ManageIQ/manageiq-appliance-build/pull/409 now that we're ready to use the upstream packages in el8 or el9 epel qpid proton 0.37.0+
To be merged with https://github.com/ManageIQ/manageiq/pull/22271
Needed for https://github.com/ManageIQ/manageiq/issues/22696
Followup: https://github.com/ManageIQ/manageiq-appliance-build/issues/560
> Use el8/9 epel qpid proton 0.37.0+

- config/base.tdl.erb
- kickstarts/base.ks.erb
- kickstarts/partials/main/repos.ks.erb
- kickstarts/partials/post/repos.ks.erb
- scripts/vmbuild.rb
> Upgrade to el9

- scripts/smoke_test.sh
- scripts/smoke_test/10-evmserverd.sh
- scripts/smoke_test/10-rpm_version.sh
- scripts/smoke_test/20-https_pings.sh
Running this will:
- Deploy a VM
- Change the default password (since we enforce that)
- Set the hostname
- Use appliance_console to configure
- encryption key
- database
- messaging
- start evmserverd
- run all tests in the smoke_test directory
- shut down the VM and clean up all files created.
> Add appliance smoke tests

- kickstarts/partials/main/repos.ks.erb
Related: https://github.com/ManageIQ/manageiq-rpm_build/pull/467
Unfortunately the repos RPM in the vault still points to mirrors.centos.org which is no longer serving Stream 8.  I patched the RPMs and posted them on rpm.manageiq.org with a change to point all repos to the vault.
> [morphy] CentOS Stream 8 is EOL

- kickstarts/base.ks.erb
- kickstarts/partials/main/bootloader.ks.erb
- kickstarts/partials/post/gce.ks.erb
It's no longer working for GCE and Azure appliances, they mark the connection as `unmanaged` and won't allow it to come up.  Also, our scripts no longer depend on the interface name in EL9.
net.ifnames=0 reverts to legacy adapter names (eth0)
biosdevname does the same for Dell systems and requires a package we don't have installed
network-scripts are no longer used by NetworkManager
> Stop using legacy network interface names (eth0)

- kickstarts/partials/packages/includes.ks.erb
Without this, gcloud compute ssh connections won't work and you can't get into the appliance
Related to #573
> GCE appliances require google-guest-agent

- kickstarts/partials/packages/includes.ks.erb
EL8 Mirrors and mirror list are no longer available.  Point to the vault instead.
This is not used for the installation itself, but for appliance use after install.  Without these packages, all dnf commands will fail to fetch the repo metadata.
> [quinteros]  Update CentOS Stream 8 repos

- kickstarts/partials/main/repos.ks.erb
CentOS Stream 8 is EOL, so packages are not getting updated anymore.  UBI8 however does still receive updates and has a newer version of ruby than CentOS Stream 8.  Adding UBI 8 repos to the appliance allows us to pull in the newer ruby so that the RPM build environment and the appliance are running the same versions of ruby.
https://github.com/msgpack/msgpack-ruby/issues/369#issuecomment-2414985034
> [QUINTEROS] Add UBI repos to pick up the newer ruby

- kickstarts/partials/main/repos.ks.erb
- kickstarts/partials/packages/includes.ks.erb
- kickstarts/partials/post/repos.ks.erb
https://github.com/ManageIQ/manageiq-rpm_build/pull/521
> [quinteros] Lock down to ruby 3.0.4 from Appstream
