kickstarts/base.ks.erb

Requires this PR first: https://github.com/ManageIQ/manageiq/pull/3390

Upgrade to bundler 1.8.4+ to work with rails-assets.

---

bin/clean_imagefactory_storage.sh
docs/creating_build_vm.txt

Please review @abellotti @brandondunne

Remove the temporary imagefactory meta and body files every few days.

---

scripts/vmbuild.rb

No need to chdir to the target directory for creating the symlink.

---

kickstarts/base.ks.erb

- Modules needed for joining Active Directories with realm.
https://trello.com/c/kky5CB6r

[auth] Adding modules needed for Active Directory

---

kickstarts/base.ks.erb

- This provides the tools for realm discovery and enrollment to assist in sssd configuration against directories such as AD or IdM.

[auth] Need the realmd package

---

kickstarts/base.ks.erb

:sparkles: https://www.ruby-lang.org/en/news/2015/08/18/ruby-2-2-3-released/ :sparkles:

Upgrade to ruby 2.2.3.

---

kickstarts/base.ks.erb

Change postgresql92 SCL references to rh-postgresql94.
https://trello.com/c/aLn9eAj1
Related PRs:
ManageIQ/manageiq#3676
ManageIQ/manageiq-appliance#9

Upgrade postgresql92 to rh-postgresql94.

---

config/tarball/exclude

Only exclude 'bin' dir at root

---

scripts/vmbuild.rb

Thanks @carbonin for reporting this

Fix NameError bug from PR #36

---

.travis.yml
README.md
Rakefile
lib/tasks/rspec.rake
scripts/Gemfile
scripts/Gemfile.lock

This will get cleaned up when we re-organize the directories but this :four_leaf_clover:  might :four_leaf_clover: work

Add travis and basic intro

---

kickstarts/base.ks.erb

Depends on: https://github.com/ManageIQ/manageiq/pull/4291
cc @blomquisg

Remove now that qpid is unsupported! :heart:

---

kickstarts/partials/main/db_fs.ks.erb
kickstarts/partials/main/disk_layout.ks.erb

Definition of the database PV belongs with the database file system definition

Moved database PV statement to partial

---

scripts/spec/data/kickstart_generator/kickstarts/base.ks.erb
scripts/spec/data/kickstart_generator/kickstarts/partials/part.ks.erb
scripts/spec/data/kickstart_generator/kickstarts/partials/part2.ks.erb
scripts/spec/data/kickstart_generator/kickstarts/partials/subdir/sub_part.ks.erb
scripts/spec/kickstart_generator_spec.rb
scripts/spec/productization_spec.rb
scripts/spec/spec_helper.rb

Add some spec tests for productization and kickstart generator classes.

Add script spec tests

---

kickstarts/partials/main/firewall.ks.erb
scripts/spec/data/kickstarts/firewall_ks_spec/kickstarts/base.ks.erb
scripts/spec/kickstart_generator_spec.rb
scripts/spec/kickstarts/partials/main/firewall_ks_spec.rb
scripts/spec/spec_helper.rb

Refactor firewall ports

---

kickstarts/partials/post/source_setup.ks.erb

Depends on https://github.com/ManageIQ/manageiq-appliance/pull/22
@jrafanie @bdunne Please review
cc @simaishi @JPrause

Move the manageiq-appliance copy and link into manageiq-appliance.

---

kickstarts/partials/packages/includes.ks.erb

@jrafanie @bdunne Please review
cc @simaishi @JPrause @dclarizio @stackus @gtanzillo @imtayadeway

Add NPM package for self service UI.

---

kickstarts/partials/post/source_setup.ks.erb

Copy motd file to display the message on the console

---

kickstarts/base.ks.erb

@jrafanie @abellotti @simaishi

Used variable for appliance repo path instead of system symlink

---

kickstarts/partials/main/disk_layout.ks.erb

Created separate file systems for:
`/tmp`
`/home`
`/var/log/audit`
`/var/log`
`/var`
`/`
https://bugzilla.redhat.com/show_bug.cgi?id=1180768
https://trello.com/c/B10qwxfk

Created filesystems for STIG compliance

---

kickstarts/partials/packages/includes.ks.erb

Related:  https://github.com/ManageIQ/manageiq/pull/3593

smem provides PSS and USS which are useful for forked processes

---

kickstarts/base.ks.erb

https://bugzilla.redhat.com/show_bug.cgi?id=1300410

Disable zeroconfig to allow access to meta-data service by cloud-init

---

kickstarts/partials/post/source_setup.ks.erb
scripts/cli.rb
scripts/kickstart_generator.rb
scripts/spec/kickstart_generator_spec.rb
scripts/vmbuild.rb

New repo located at https://github.com/ManageIQ/manageiq-ui-self_service
Related to https://github.com/ManageIQ/manageiq-appliance/pull/56 and ManageIQ/manageiq#6631

Extract SSUI into its own repo

---

kickstarts/partials/main/repos.ks.erb
kickstarts/partials/packages/includes.ks.erb
kickstarts/partials/post/repos.ks.erb

Pull pglogical packages from copr repo.
@Fryguy @gtanzillo @jrafanie

Added pglogical packages and repos

---

.gitignore
bin/kickstart_build.rb
scripts/Gemfile

Provide a mechanism for developers to test kickstart ERBs changes

---

kickstarts/base.ks.erb
kickstarts/partials/main/bootloader.ks.erb

https://bugzilla.redhat.com/show_bug.cgi?id=1278084

Direct /dev/console to /dev/ttyS0 for openstack

---

kickstarts/partials/packages/includes.ks.erb

Needed as a dependency for the rugged gem added in https://github.com/ManageIQ/manageiq/pull/3807

Install cmake package

---

kickstarts/partials/packages/includes.ks.erb

https://bugzilla.redhat.com/show_bug.cgi?id=1318290

Install netcat and telnet tools

---

kickstarts/partials/packages/includes.ks.erb

This also is the same name as the RHEL package
@jrafanie

Use full package name for nmap-ncat

---

kickstarts/partials/post/firewalld.ks.erb

https://github.com/ManageIQ/manageiq/issues/2451

Closed ports for proxies using the old console implementation

---

kickstarts/partials/packages/includes.ks.erb

This is to resolve BZ 1322611
@simaishi can you please review.

Add package hyperv-daemons for vhd appliance

---

kickstarts/base.ks.erb
kickstarts/partials/post/ui_compile.ks.erb

Related PR: https://github.com/ManageIQ/manageiq-appliance/pull/67

Move compile assets, sti loader and SSUI from cfme-setup

---

kickstarts/base.ks.erb

Related PRs:
https://github.com/ManageIQ/manageiq/pull/7470
https://github.com/ManageIQ/manageiq-appliance/pull/62
https://github.com/ManageIQ/manageiq_docs/pull/20
https://github.com/ManageIQ/guides/pull/120

Renamed cfme in configuration files to manageiq

---

bin/nightly-build.sh

Requires #125 to be merged and backported to darga.

Darga nightly build

---

kickstarts/base.ks.erb
kickstarts/partials/main/repos.ks.erb
kickstarts/partials/packages/includes.ks.erb
kickstarts/partials/post/gce.ks.erb
kickstarts/partials/post/repos.ks.erb
kickstarts/partials/post/systemd.ks.erb

- Add sshd/ssh configuration
- Lock root account
- Install Google image packages (google-compute-engine and google-config)
- Remove kernel security settings as google image package provides them
- Remove cloud-init
https://bugzilla.redhat.com/show_bug.cgi?id=1338741

Secure GCE image

---

kickstarts/partials/main/db_fs.ks.erb
kickstarts/partials/packages/includes.ks.erb
kickstarts/partials/post/db_init.ks.erb

Changed package names and paths for postgresql95

Change package names and paths for PostgreSQL 9.5

---

kickstarts/partials/packages/includes.ks.erb

Add repmgr package for postgresql HA implementation.
https://www.pivotaltracker.com/story/show/126396993

Add rh-repmgr95 package

---

kickstarts/partials/post/firewalld.ks.erb

Fixes #108 
@bdunne @abellotti

Removed services duplicated by ports in firewall config

---

kickstarts/base.ks.erb
kickstarts/partials/post/vagrant.ks.erb

This is a first version. Current it is limited to the VirtualBox format
(which is by far the most common format). Also uploading to the
Hashicorp Altas is not yet supported.
(Cherry picked from ca57df70bd4dbb1a50dfa0eeaca07737727d093a)

[DARGA] Add support for Vagrant

---

config/base.tdl
config/base_azure.tdl
kickstarts/partials/main/disk_layout.ks.erb
kickstarts/partials/post/source_setup.ks.erb

https://www.pivotaltracker.com/n/projects/1608513/stories/126710339

Increase the size of the default upstream log volume

---

bin/nightly-build.sh

Then, BRANCH will be the only edit needed when we cut a new branch.

Explicitly specify branch even for 'master'

---

bin/nightly-build.sh

BRANCH will be the only edit needed when we cut a new branch
Master PR: https://github.com/ManageIQ/manageiq-appliance-build/pull/163
Cherry-picked and changed the branch name to 'euwe'.

[EUWE] Explicitly specify branch even for 'master'

---

kickstarts/partials/post/ruby_install.ks.erb

Uptadte to v0.6.0

---

bin/kickstart_build.rb
kickstarts/partials/packages/includes.ks.erb
kickstarts/partials/post/bundler.ks.erb
kickstarts/partials/post/source_setup.ks.erb
kickstarts/partials/post/ui_compile.ks.erb
scripts/cli.rb
scripts/kickstart_generator.rb
scripts/spec/cli_spec.rb
scripts/spec/kickstart_generator_spec.rb
scripts/vmbuild.rb

Updated as per README in manageiq-ui-service repo.
Built on top of https://github.com/ManageIQ/manageiq-appliance-build/pull/180
~~One remaining issue - the app expects to see 'index.html' in public/ui/service directory.  What currently comes out of the build is dynamically generated name. e.g. index-db4658ee4f.html. cc @AllenBW~~

ServiceUI build step update

---

scripts/vmbuild.rb

Ovirt/RHV 4.1 supports qcow2, but not ova import. 3.x supports ova import, but not qcow2. So we need to create 2 images until all supported Ovirt/RHV versions can share 1 format.
Made it ovirt/qcow2 specific rather than adding 'generic' way to support multiple formats for a provider as:
- We're not planning to support 2 images for any other provider (we want to reduce # of images, not add more!)
- Even if we need to create 2 images for another provider in the future, depending on what needs to be built for which provider, process will be different
https://bugzilla.redhat.com/show_bug.cgi?id=1410020

For ovirt, create both ova and qcow2

---

.gitignore
.rubocop.yml
.rubocop_cc.yml
.rubocop_local.yml

Add rubocop config files

---

kickstarts/partials/packages/includes.ks.erb

Also, `tree` because it's useful.

Add vim for syntax highlighting on appliances

---

kickstarts/partials/post/ui_compile.ks.erb

Moved in https://github.com/ManageIQ/manageiq/pull/14536
cc @himdel

Update bower command as it moved to ui-classic

---

kickstarts/partials/post/ui_compile.ks.erb

SUI fix for appliance build.  Ensured we only install production dependencies

Specified only production dependencies be installed

---

kickstarts/partials/packages/includes.ks.erb

https://bugzilla.redhat.com/show_bug.cgi?id=1438562

Add samba-common-tools

---

kickstarts/partials/packages/includes.ks.erb

Fixes https://github.com/ManageIQ/manageiq/issues/15856
cc @gtanzillo @blomquisg

Add screen package

---

kickstarts/partials/main/repos.ks.erb
kickstarts/partials/post/repos.ks.erb

From now on, we can fork the master repo into a branch name repo
at the same time that we create the release branch in this repo.
This allows us to change package versions without affecting previous
releases more easily.

Use a master copr repo on the master branch

---

bin/nightly-build.sh
config/ova.json
kickstarts/partials/main/repos.ks.erb
kickstarts/partials/post/repos.ks.erb
scripts/cli.rb
scripts/docbuild.rb
scripts/spec/cli_spec.rb

[GAPRINDASHVILI] Updates for Gaprindashvili

---

kickstarts/partials/packages/includes.ks.erb
kickstarts/partials/post/systemd.ks.erb

This is required for https://github.com/ManageIQ/manageiq/pull/16205

Add the docker package to run awx locally on the appliance

---

kickstarts/partials/packages/includes.ks.erb

Needed for https://github.com/ManageIQ/manageiq/pull/16852
cc @Fryguy @gtanzillo

Add sqlite-devel package

---

kickstarts/partials/packages/includes.ks.erb

Include RPM mod_auth_openidc for OpenID-Connect support.

Add support for OpenID-Connect

---

LICENSE.txt
README.md

Closes https://github.com/ManageIQ/manageiq-appliance-build/issues/40

Add Apache-2.0 license

---

kickstarts/partials/main/repos.ks.erb
kickstarts/partials/packages/includes.ks.erb
kickstarts/partials/post/repos.ks.erb

This currently installs ansible-runner 1.0.5
cc @Ladas @Fryguy

Add ansible-runner

---

kickstarts/base.ks.erb
kickstarts/partials/post/ovirt_ansible.ks.erb

Add python-ovirt-engine-sdk4
https://bugzilla.redhat.com/show_bug.cgi?id=1610768
Add ovirt-ansible-roles
https://bugzilla.redhat.com/show_bug.cgi?id=1610798
cc @mwperina @Fryguy

Add RPMs needed for Ansible playbooks and roles for oVirt

---

config/ova.json
kickstarts/partials/post/repos.ks.erb

Follow-up for https://github.com/ManageIQ/manageiq-appliance-build/pull/283

[HAMMER] Updates for Hammer branch

---

kickstarts/partials/post/ruby_install.ks.erb

cc @jrafanie 
Change to container image is coming up next... ping'ed @bdunne to get a new branch created on container-ruby repo.

[GAPRINDASHVILI] Update to ruby 2.3.8

---

kickstarts/partials/packages/includes.ks.erb

Can only be merged after https://github.com/ManageIQ/manageiq/pull/18686 and https://github.com/ManageIQ/manageiq-appliance/pull/236

Remove pglogical package

---

kickstarts/partials/main/repos.ks.erb

Updating node to 10.x to match downstream appliance.
cc @himdel

Update to node 10

---

kickstarts/partials/post/ovirt_ansible.ks.erb

4.3 is the current version and matches with what downstream build uses.

Update to ovirt 4.3

---

kickstarts/partials/post/ui_compile.ks.erb

https://github.com/ManageIQ/manageiq-ui-classic/pull/4735

Remove bower

---

README.md
scripts/Gemfile
scripts/uploader.rb

- Switch from fog to rest-client
- Add the "X-Delete-At" header to nightly uploads so that images are automatically expired and cleaned up after 8 weeks

Setting delete at

---

scripts/docbuild.rb

Closes https://github.com/ManageIQ/manageiq-appliance-build/issues/166

Use asciibinder instead of ascii_binder

---

scripts/vmbuild.rb

Currently the script exits when imagefactory fails and we don't build the rest of the images. We should just skip the failed one and go to the next.

Don't kill script when imagefactory fails

---

scripts/uploader.rb

Copy to devel

---

README.md

Also cleaned up outdated information.

Update build machine setup instruction to use CentOS 8

---

bin/nightly-build.sh
bin/release-build.sh

Follow-up for #375.  Should have tested with cron job...

Fix path to container-build.sh

---

README.md
kickstarts/base.ks.erb
kickstarts/centos8_build_machine.ks

- Add a kickstart file for the build machine
- Add an example iPXE boot script
- Remove some installation documentation from the README

Kickstart the build appliance

---

kickstarts/partials/post/ruby_install.ks.erb

Updating to 2.6.x, as per discussion with @jrafanie and @Fryguy.  2.6.5 is the latest 2.6 release.

Update to ruby 2.6.5

---

CHANGELOG.md

[JANSA] Changelog Jansa

---

scripts/Gemfile

Needed for https://github.com/ManageIQ/manageiq-appliance-build/pull/391

Add awesome_spawn

---

bin/container-build.sh

BUILD_REF added in https://github.com/ManageIQ/manageiq-pods/pull/382

Add BUILD_REF to podified build

---

scripts/Gemfile

Follow up for https://github.com/ManageIQ/manageiq-appliance-build/pull/412

Add aws-sdk-s3 gem, needed for digital ocean upload

---

README.md
kickstarts/base.ks.erb
kickstarts/partials/post/gce.ks.erb
kickstarts/partials/post/ovirt_ansible.ks.erb
kickstarts/partials/post/python_modules.ks.erb
kickstarts/partials/post/repos.ks.erb

`dnf` is the default in CentOS 8.

Replace yum with dnf

---

kickstarts/base.ks.erb

Enforce root password reset at first login

---

kickstarts/base.ks.erb

Requires https://github.com/ManageIQ/manageiq-appliance/pull/289 and https://github.com/ManageIQ/manageiq-rpm_build/pull/73
A part of #429

Create rpm manifest

---

scripts/uploader.rb

Fix undefined method `[]=' for nil:NilClass

---

scripts/uploader.rb

releases.manageiq.org now points to DigitalOcean
cc @simaishi

Stop uploading to Rackspace

---

kickstarts/partials/main/repos.ks.erb

Follow up to https://github.com/ManageIQ/manageiq-appliance/pull/293
@simaishi Please review.

Align repo names with the official names

---

kickstarts/partials/main/repos.ks.erb
kickstarts/partials/post/repos.ks.erb

No RPM is coming from PowerTools repo, so removing.

Remove PowerTools repo - no longer used

---

.codeclimate.yml
.rubocop.yml
.rubocop_cc.yml

Depends on: https://github.com/ManageIQ/miq_bot/pull/506

Switch to manageiq-style

---

bin/container-build.sh

Addresses https://github.com/ManageIQ/manageiq-pods/pull/682#issuecomment-777638601

Changes required by manageiq-pods#682

---

bin/container-build.sh

Built on #464 
Add the registry to the docker commands to prevent push failures

Add registry to the docker commands

---

config/base.tdl.erb

Update to the current CentOS 8.y

Update the base image for the appliance build

---

bin/nightly-build.sh
scripts/cli.rb

Change fileshare copy default to false
(cherry picked from commit 7b46c03df202aad8bb5eaf68ee9b43148ffb97c2)

[JANSA] Jansa backport 467

---

bin/nightly-build.sh
scripts/cli.rb

Change fileshare copy default to false
(cherry picked from commit 7b46c03df202aad8bb5eaf68ee9b43148ffb97c2)

[LASKER] Backport: Merge pull request #467 from bdunne/fileshare

---

kickstarts/partials/post/appliance_init.ks.erb

Accidentally introduced in #470

Remove duplicate initialization

---

README.md
config/base.tdl.erb
kickstarts/centos8_build_machine.ks
kickstarts/partials/main/repos.ks.erb

Part of https://github.com/ManageIQ/manageiq-appliance-build/issues/459
@bdunne Please review.  I actually have no idea if this works, as I don't know how to do builds locally - will need your help at some point.

Move to CentOS Stream

---

kickstarts/partials/post/python_modules.ks.erb

See also https://github.com/ManageIQ/manageiq-rpm_build/pull/142

Bump pyyaml to 5.4 to handle CVEs

---

kickstarts/partials/main/repos.ks.erb
kickstarts/partials/post/repos.ks.erb

Appliance-side change similar to ManageIQ/manageiq-pods#766
@jrafanie Please review.  cc @agrare  @bdunne

Remove ovirt repo

---

config/base.tdl.erb

This ISO is already in place on the build machines for master and morphy

Update to latest CentOS 8 Stream ISO

---

config/base.tdl.erb

Backport of: https://github.com/ManageIQ/manageiq-appliance-build/pull/497

[MORPHY] Update to latest CentOS 8 Stream ISO

---

kickstarts/base.ks.erb

Update node version to 16
Issue:https://github.com/ManageIQ/manageiq-ui-classic/issues/7930
@miq-bot assign @Fryguy 
@miq-bot add_reviewer @Fryguy 
@miq-bot add-label dependencies

Update node version

---

kickstarts/base.ks.erb

Issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/7930
@miq_bot assign @fryguy
@miq_bot add_reviewer @fryguy
@miq_bot add-label dependencies, najdorf/yes?

Downgrade node version to 14

---

kickstarts/partials/packages/includes.ks.erb

Provide a way to include extra packages similar to repos-extra

---

kickstarts/partials/post/python_modules.ks.erb

Fixes issues where make is not available to build the python resources.

Ensure make is available on all platforms

---

kickstarts/partials/post/python_modules.ks.erb

Update python dependencies for CVEs

---

kickstarts/partials/post/python_modules.ks.erb

Ensure psutil is installed for all pythons

---

kickstarts/partials/post/python_modules.ks.erb

This reverts commit 136510778d2ca4e7a6114746ea9b5ea5addbe195, reversing changes made to d6b192c5bb92d8742fd9f9afd1bf758fe039057b.
@agrare Please review.
Reverting this change in favor of the one in #529

Revert "Merge pull request #528 from Fryguy/psutils"

---

kickstarts/base.ks.erb

Use PG 13 module from stream

---

kickstarts/partials/main/repos.ks.erb
kickstarts/partials/post/repos.ks.erb

Remove the ansible-runner repository now that we've upgraded runner

---

kickstarts/base.ks.erb

@agrare Please review cc @bdunne

Add nobest to deal with ansible 5/6 upgrade issues

---

README.md
scripts/vmbuild.rb

Also remove references to file_rdu

Remove fileshare logic as it hasn't been used in years

---

scripts/uploader.rb

Typo env should be ENV

---

kickstarts/partials/post/python_modules.ks.erb

morphy backport of https://github.com/ManageIQ/manageiq-rpm_build/pull/403
@agrare Please review

[MORPHY] Bump ipaddress python package

---

.github/workflows/build_appliances.yaml
.github/workflows/ci.yaml

Update actions/checkout version to v4

Update actions/checkout version to v4

---

kickstarts/base.ks.erb

Otherwise root can't log into the cockpit web UI

Remove root from the cockpit disallowed-users list

---

kickstarts/partials/main/repos.ks.erb

This reverts commit 5a12806e7f9f063ea4c0868ec186ae64a94954ca.

[quinteros] Revert "Changes after new branch quinteros"

---

scripts/smoke_test.sh

- Document dependencies
- Ensure boot device is `hd`
- Switch graphics to VNC for those not on linux
- Prefer .local rather than .xip.io

Misc updates for CentOS Stream 9 hosts

---

kickstarts/partials/main/bootloader.ks.erb

Enable the serial console for use in kubevirt

---

kickstarts/partials/main/repos.ks.erb

Curl is failing to pull the repodata.xml on these repos.  There's a 301 to redirect to https, but maybe anaconda isn't following it??

[MORPHY] Switch to https

---

kickstarts/base.ks.erb

For: https://github.com/ManageIQ/manageiq/pull/23142

Set ruby stream to 3.3

---

bin/deploy_kubevirt_vm

Note on the first commit I gave you and @kschanrtp Co-Authored-By. I'm not sure if anyone else was involved, so let me know.
There are other changes I want to make later such as cleaning up some unneeded stuff, simplifying some things, short-circuiting things (like when KubeVirt is already installed), but I will do follow up PRs.  For now, this successfully creates a VM on OCP.

Add script to deploy a VM to KubeVirt/OSV

---

bin/deploy_kubevirt_vm

Fix typos in deploy script

---

bin/deploy_kubevirt_vm

@jrafanie Please review.  See individual commits for changes.
- Add simpler login check and add a storageclass check
- Add a pre-check for KubeVirt and CDI installation
- Simplify the datavolume check and report percentage complete
- Remove the correct kubevirt_known_hosts file
I could break these up into separate PRs if you want, but that's a lot of work LOL

Updates to deploy_kubevirt_vm
